package com.exampleariba.aribasoup.gerado;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.2.0
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class QBSBPSUITERplctReqBiddingCharc extends AttributeContainer implements KvmSerializable
{

    
    public Boolean MinorityOwnedIndicator;
    
    public java.util.Date MinorityOwnedCertificateExpirationDate;
    
    public Boolean WomenOwnedIndicator;
    
    public java.util.Date WomenOwnedCertificateExpirationDate;
    
    public Boolean SurrogateBiddingAllowedIndicator;
    
    public Boolean OfflineBiddingIndicator;
    
    public String actionCode;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,QBSExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }
        if (inObj.hasAttribute("actionCode"))
        {	
            java.lang.Object j = inObj.getAttribute("actionCode");
            if (j != null)
            {
                actionCode = j.toString();
            }
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,QBSExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("MinorityOwnedIndicator"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.MinorityOwnedIndicator = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.MinorityOwnedIndicator = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("MinorityOwnedCertificateExpirationDate"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.MinorityOwnedCertificateExpirationDate = QBSHelper.ConvertFromWebService(j.toString());
                    }
                }
                else if (obj instanceof java.util.Date){
                    this.MinorityOwnedCertificateExpirationDate = (java.util.Date)obj;
                }
            }
            return true;
        }
        if (info.name.equals("WomenOwnedIndicator"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.WomenOwnedIndicator = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.WomenOwnedIndicator = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("WomenOwnedCertificateExpirationDate"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.WomenOwnedCertificateExpirationDate = QBSHelper.ConvertFromWebService(j.toString());
                    }
                }
                else if (obj instanceof java.util.Date){
                    this.WomenOwnedCertificateExpirationDate = (java.util.Date)obj;
                }
            }
            return true;
        }
        if (info.name.equals("SurrogateBiddingAllowedIndicator"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.SurrogateBiddingAllowedIndicator = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.SurrogateBiddingAllowedIndicator = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("OfflineBiddingIndicator"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.OfflineBiddingIndicator = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.OfflineBiddingIndicator = (Boolean)obj;
                }
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.MinorityOwnedIndicator!=null?this.MinorityOwnedIndicator:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.MinorityOwnedCertificateExpirationDate!=null?QBSHelper.getDateFormat().format(this.MinorityOwnedCertificateExpirationDate):SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.WomenOwnedIndicator!=null?this.WomenOwnedIndicator:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.WomenOwnedCertificateExpirationDate!=null?QBSHelper.getDateFormat().format(this.WomenOwnedCertificateExpirationDate):SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.SurrogateBiddingAllowedIndicator!=null?this.SurrogateBiddingAllowedIndicator:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.OfflineBiddingIndicator!=null?this.OfflineBiddingIndicator:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 6;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "MinorityOwnedIndicator";
            info.namespace= "";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "MinorityOwnedCertificateExpirationDate";
            info.namespace= "";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "WomenOwnedIndicator";
            info.namespace= "";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "WomenOwnedCertificateExpirationDate";
            info.namespace= "";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "SurrogateBiddingAllowedIndicator";
            info.namespace= "";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "OfflineBiddingIndicator";
            info.namespace= "";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }



    @Override
    public int getAttributeCount() {
        return 1;
    }
    
    @Override
    public void getAttributeInfo(int index, AttributeInfo info) {
        if(index==0)
        {
            info.name = "actionCode";
            info.namespace= "";
            if(this.actionCode!=null)
            {
                info.setValue(this.actionCode);
            }
            
        }
    }

    @Override
    public void getAttribute(int i, AttributeInfo attributeInfo) {

    }

    @Override
    public void setAttribute(AttributeInfo attributeInfo) {

    }    
}

