package com.exampleariba.aribasoup.gerado;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.2.0
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class QBSBPSUITERplctReqAddrInfoAddrPostlAddr extends AttributeContainer implements KvmSerializable
{

    
    public QBSAddressRepresentationCode AddressRepresentationCode;
    
    public String CountryCode;
    
    public QBSRegionCode RegionCode;
    
    public String CityName;
    
    public String AdditionalCityName;
    
    public String DistrictName;
    
    public String StreetPostalCode;
    
    public String POBoxPostalCode;
    
    public String CompanyPostalCode;
    
    public String StreetPrefixName;
    
    public String AdditionalStreetPrefixName;
    
    public String StreetName;
    
    public String StreetSuffixName;
    
    public String AdditionalStreetSuffixName;
    
    public String HouseID;
    
    public String AdditionalHouseID;
    
    public String BuildingID;
    
    public String RoomID;
    
    public String FloorID;
    
    public String CareOfName;
    
    public QBSMailNonDeliveryReasonCode StreetAddressMailNonDeliveryReasonCode;
    
    public String POBoxDeviatingCountryCode;
    
    public QBSRegionCode POBoxDeviatingRegionCode;
    
    public String POBoxDeviatingCityName;
    
    public String POBoxLobbyName;
    
    public String POBoxID;
    
    public QBSMailNonDeliveryReasonCode POBoxAddressMailNonDeliveryReasonCode;
    
    public Boolean POBoxIDVisibleIndicator;
    
    public QBSIdentifier POBoxDeliveryServiceID;
    
    public QBSCode POBoxDeliveryServiceTypeCode;
    
    public QBSTaxJurisdictionCode TaxJurisdictionCode;
    
    public String TimeZoneCode;
    
    public QBSTransportationZoneID TransportationZoneID;
    
    public QBSRegionalStructureElementGroupCode RegionalStructureElementGroupCode;
    
    public String RegionalStructureAddressConsistencyStatusCode;
    
    public QBSRegionalStructureCityCode RegionalStructureCityCode;
    
    public QBSRegionalStructureCityCode AdditionalRegionalStructureCityCode;
    
    public QBSRegionalStructureCityCode POBoxDeviatingRegionalStructureCityCode;
    
    public QBSRegionalStructureDistrictCode RegionalStructureDistrictCode;
    
    public QBSRegionalStructureStreetCode RegionalStructureStreetCode;
    
    public String ExtendedBuildingID;
    
    public String actionCode;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,QBSExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }
        if (inObj.hasAttribute("actionCode"))
        {	
            java.lang.Object j = inObj.getAttribute("actionCode");
            if (j != null)
            {
                actionCode = j.toString();
            }
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,QBSExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("AddressRepresentationCode"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.AddressRepresentationCode = (QBSAddressRepresentationCode)__envelope.get(j,QBSAddressRepresentationCode.class,false);
            }
            return true;
        }
        if (info.name.equals("CountryCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.CountryCode = j.toString();
                    }
                }
                else{
                    this.CountryCode = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("RegionCode"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.RegionCode = (QBSRegionCode)__envelope.get(j,QBSRegionCode.class,false);
            }
            return true;
        }
        if (info.name.equals("CityName"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.CityName = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.CityName = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("AdditionalCityName"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.AdditionalCityName = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.AdditionalCityName = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("DistrictName"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.DistrictName = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.DistrictName = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("StreetPostalCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.StreetPostalCode = j.toString();
                    }
                }
                else{
                    this.StreetPostalCode = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("POBoxPostalCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.POBoxPostalCode = j.toString();
                    }
                }
                else{
                    this.POBoxPostalCode = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("CompanyPostalCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.CompanyPostalCode = j.toString();
                    }
                }
                else{
                    this.CompanyPostalCode = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("StreetPrefixName"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.StreetPrefixName = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.StreetPrefixName = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("AdditionalStreetPrefixName"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.AdditionalStreetPrefixName = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.AdditionalStreetPrefixName = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("StreetName"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.StreetName = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.StreetName = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("StreetSuffixName"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.StreetSuffixName = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.StreetSuffixName = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("AdditionalStreetSuffixName"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.AdditionalStreetSuffixName = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.AdditionalStreetSuffixName = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("HouseID"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.HouseID = j.toString();
                    }
                }
                else{
                    this.HouseID = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("AdditionalHouseID"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.AdditionalHouseID = j.toString();
                    }
                }
                else{
                    this.AdditionalHouseID = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("BuildingID"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.BuildingID = j.toString();
                    }
                }
                else{
                    this.BuildingID = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("RoomID"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.RoomID = j.toString();
                    }
                }
                else{
                    this.RoomID = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("FloorID"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.FloorID = j.toString();
                    }
                }
                else{
                    this.FloorID = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("CareOfName"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.CareOfName = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.CareOfName = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("StreetAddressMailNonDeliveryReasonCode"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.StreetAddressMailNonDeliveryReasonCode = (QBSMailNonDeliveryReasonCode)__envelope.get(j,QBSMailNonDeliveryReasonCode.class,false);
            }
            return true;
        }
        if (info.name.equals("POBoxDeviatingCountryCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.POBoxDeviatingCountryCode = j.toString();
                    }
                }
                else{
                    this.POBoxDeviatingCountryCode = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("POBoxDeviatingRegionCode"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.POBoxDeviatingRegionCode = (QBSRegionCode)__envelope.get(j,QBSRegionCode.class,false);
            }
            return true;
        }
        if (info.name.equals("POBoxDeviatingCityName"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.POBoxDeviatingCityName = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.POBoxDeviatingCityName = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("POBoxLobbyName"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.POBoxLobbyName = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.POBoxLobbyName = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("POBoxID"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.POBoxID = j.toString();
                    }
                }
                else{
                    this.POBoxID = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("POBoxAddressMailNonDeliveryReasonCode"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.POBoxAddressMailNonDeliveryReasonCode = (QBSMailNonDeliveryReasonCode)__envelope.get(j,QBSMailNonDeliveryReasonCode.class,false);
            }
            return true;
        }
        if (info.name.equals("POBoxIDVisibleIndicator"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.POBoxIDVisibleIndicator = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.POBoxIDVisibleIndicator = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("POBoxDeliveryServiceID"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.POBoxDeliveryServiceID = (QBSIdentifier)__envelope.get(j,QBSIdentifier.class,false);
            }
            return true;
        }
        if (info.name.equals("POBoxDeliveryServiceTypeCode"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.POBoxDeliveryServiceTypeCode = (QBSCode)__envelope.get(j,QBSCode.class,false);
            }
            return true;
        }
        if (info.name.equals("TaxJurisdictionCode"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.TaxJurisdictionCode = (QBSTaxJurisdictionCode)__envelope.get(j,QBSTaxJurisdictionCode.class,false);
            }
            return true;
        }
        if (info.name.equals("TimeZoneCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.TimeZoneCode = j.toString();
                    }
                }
                else{
                    this.TimeZoneCode = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("TransportationZoneID"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.TransportationZoneID = (QBSTransportationZoneID)__envelope.get(j,QBSTransportationZoneID.class,false);
            }
            return true;
        }
        if (info.name.equals("RegionalStructureElementGroupCode"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.RegionalStructureElementGroupCode = (QBSRegionalStructureElementGroupCode)__envelope.get(j,QBSRegionalStructureElementGroupCode.class,false);
            }
            return true;
        }
        if (info.name.equals("RegionalStructureAddressConsistencyStatusCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.RegionalStructureAddressConsistencyStatusCode = j.toString();
                    }
                }
                else{
                    this.RegionalStructureAddressConsistencyStatusCode = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("RegionalStructureCityCode"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.RegionalStructureCityCode = (QBSRegionalStructureCityCode)__envelope.get(j,QBSRegionalStructureCityCode.class,false);
            }
            return true;
        }
        if (info.name.equals("AdditionalRegionalStructureCityCode"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.AdditionalRegionalStructureCityCode = (QBSRegionalStructureCityCode)__envelope.get(j,QBSRegionalStructureCityCode.class,false);
            }
            return true;
        }
        if (info.name.equals("POBoxDeviatingRegionalStructureCityCode"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.POBoxDeviatingRegionalStructureCityCode = (QBSRegionalStructureCityCode)__envelope.get(j,QBSRegionalStructureCityCode.class,false);
            }
            return true;
        }
        if (info.name.equals("RegionalStructureDistrictCode"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.RegionalStructureDistrictCode = (QBSRegionalStructureDistrictCode)__envelope.get(j,QBSRegionalStructureDistrictCode.class,false);
            }
            return true;
        }
        if (info.name.equals("RegionalStructureStreetCode"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.RegionalStructureStreetCode = (QBSRegionalStructureStreetCode)__envelope.get(j,QBSRegionalStructureStreetCode.class,false);
            }
            return true;
        }
        if (info.name.equals("ExtendedBuildingID"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ExtendedBuildingID = j.toString();
                    }
                }
                else{
                    this.ExtendedBuildingID = obj.toString();
                }
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.AddressRepresentationCode!=null?this.AddressRepresentationCode.getSimpleValue():null;
        }
        if(propertyIndex==1)
        {
            return this.CountryCode!=null?this.CountryCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.RegionCode!=null?this.RegionCode.getSimpleValue():null;
        }
        if(propertyIndex==3)
        {
            return this.CityName!=null?this.CityName:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.AdditionalCityName!=null?this.AdditionalCityName:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.DistrictName!=null?this.DistrictName:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.StreetPostalCode!=null?this.StreetPostalCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==7)
        {
            return this.POBoxPostalCode!=null?this.POBoxPostalCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==8)
        {
            return this.CompanyPostalCode!=null?this.CompanyPostalCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==9)
        {
            return this.StreetPrefixName!=null?this.StreetPrefixName:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==10)
        {
            return this.AdditionalStreetPrefixName!=null?this.AdditionalStreetPrefixName:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==11)
        {
            return this.StreetName!=null?this.StreetName:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==12)
        {
            return this.StreetSuffixName!=null?this.StreetSuffixName:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==13)
        {
            return this.AdditionalStreetSuffixName!=null?this.AdditionalStreetSuffixName:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==14)
        {
            return this.HouseID!=null?this.HouseID:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==15)
        {
            return this.AdditionalHouseID!=null?this.AdditionalHouseID:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==16)
        {
            return this.BuildingID!=null?this.BuildingID:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==17)
        {
            return this.RoomID!=null?this.RoomID:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==18)
        {
            return this.FloorID!=null?this.FloorID:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==19)
        {
            return this.CareOfName!=null?this.CareOfName:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==20)
        {
            return this.StreetAddressMailNonDeliveryReasonCode!=null?this.StreetAddressMailNonDeliveryReasonCode.getSimpleValue():null;
        }
        if(propertyIndex==21)
        {
            return this.POBoxDeviatingCountryCode!=null?this.POBoxDeviatingCountryCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==22)
        {
            return this.POBoxDeviatingRegionCode!=null?this.POBoxDeviatingRegionCode.getSimpleValue():null;
        }
        if(propertyIndex==23)
        {
            return this.POBoxDeviatingCityName!=null?this.POBoxDeviatingCityName:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==24)
        {
            return this.POBoxLobbyName!=null?this.POBoxLobbyName:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==25)
        {
            return this.POBoxID!=null?this.POBoxID:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==26)
        {
            return this.POBoxAddressMailNonDeliveryReasonCode!=null?this.POBoxAddressMailNonDeliveryReasonCode.getSimpleValue():null;
        }
        if(propertyIndex==27)
        {
            return this.POBoxIDVisibleIndicator!=null?this.POBoxIDVisibleIndicator:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==28)
        {
            return this.POBoxDeliveryServiceID!=null?this.POBoxDeliveryServiceID.getSimpleValue():null;
        }
        if(propertyIndex==29)
        {
            return this.POBoxDeliveryServiceTypeCode!=null?this.POBoxDeliveryServiceTypeCode.getSimpleValue():null;
        }
        if(propertyIndex==30)
        {
            return this.TaxJurisdictionCode!=null?this.TaxJurisdictionCode.getSimpleValue():null;
        }
        if(propertyIndex==31)
        {
            return this.TimeZoneCode!=null?this.TimeZoneCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==32)
        {
            return this.TransportationZoneID!=null?this.TransportationZoneID.getSimpleValue():null;
        }
        if(propertyIndex==33)
        {
            return this.RegionalStructureElementGroupCode!=null?this.RegionalStructureElementGroupCode.getSimpleValue():null;
        }
        if(propertyIndex==34)
        {
            return this.RegionalStructureAddressConsistencyStatusCode!=null?this.RegionalStructureAddressConsistencyStatusCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==35)
        {
            return this.RegionalStructureCityCode!=null?this.RegionalStructureCityCode.getSimpleValue():null;
        }
        if(propertyIndex==36)
        {
            return this.AdditionalRegionalStructureCityCode!=null?this.AdditionalRegionalStructureCityCode.getSimpleValue():null;
        }
        if(propertyIndex==37)
        {
            return this.POBoxDeviatingRegionalStructureCityCode!=null?this.POBoxDeviatingRegionalStructureCityCode.getSimpleValue():null;
        }
        if(propertyIndex==38)
        {
            return this.RegionalStructureDistrictCode!=null?this.RegionalStructureDistrictCode.getSimpleValue():null;
        }
        if(propertyIndex==39)
        {
            return this.RegionalStructureStreetCode!=null?this.RegionalStructureStreetCode.getSimpleValue():null;
        }
        if(propertyIndex==40)
        {
            return this.ExtendedBuildingID!=null?this.ExtendedBuildingID:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 41;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "AddressRepresentationCode";
            info.namespace= "";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "CountryCode";
            info.namespace= "";
        }
        if(propertyIndex==2)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "RegionCode";
            info.namespace= "";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "CityName";
            info.namespace= "";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "AdditionalCityName";
            info.namespace= "";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "DistrictName";
            info.namespace= "";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "StreetPostalCode";
            info.namespace= "";
        }
        if(propertyIndex==7)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "POBoxPostalCode";
            info.namespace= "";
        }
        if(propertyIndex==8)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "CompanyPostalCode";
            info.namespace= "";
        }
        if(propertyIndex==9)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "StreetPrefixName";
            info.namespace= "";
        }
        if(propertyIndex==10)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "AdditionalStreetPrefixName";
            info.namespace= "";
        }
        if(propertyIndex==11)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "StreetName";
            info.namespace= "";
        }
        if(propertyIndex==12)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "StreetSuffixName";
            info.namespace= "";
        }
        if(propertyIndex==13)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "AdditionalStreetSuffixName";
            info.namespace= "";
        }
        if(propertyIndex==14)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "HouseID";
            info.namespace= "";
        }
        if(propertyIndex==15)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "AdditionalHouseID";
            info.namespace= "";
        }
        if(propertyIndex==16)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "BuildingID";
            info.namespace= "";
        }
        if(propertyIndex==17)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "RoomID";
            info.namespace= "";
        }
        if(propertyIndex==18)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "FloorID";
            info.namespace= "";
        }
        if(propertyIndex==19)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "CareOfName";
            info.namespace= "";
        }
        if(propertyIndex==20)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "StreetAddressMailNonDeliveryReasonCode";
            info.namespace= "";
        }
        if(propertyIndex==21)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "POBoxDeviatingCountryCode";
            info.namespace= "";
        }
        if(propertyIndex==22)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "POBoxDeviatingRegionCode";
            info.namespace= "";
        }
        if(propertyIndex==23)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "POBoxDeviatingCityName";
            info.namespace= "";
        }
        if(propertyIndex==24)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "POBoxLobbyName";
            info.namespace= "";
        }
        if(propertyIndex==25)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "POBoxID";
            info.namespace= "";
        }
        if(propertyIndex==26)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "POBoxAddressMailNonDeliveryReasonCode";
            info.namespace= "";
        }
        if(propertyIndex==27)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "POBoxIDVisibleIndicator";
            info.namespace= "";
        }
        if(propertyIndex==28)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "POBoxDeliveryServiceID";
            info.namespace= "";
        }
        if(propertyIndex==29)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "POBoxDeliveryServiceTypeCode";
            info.namespace= "";
        }
        if(propertyIndex==30)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "TaxJurisdictionCode";
            info.namespace= "";
        }
        if(propertyIndex==31)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "TimeZoneCode";
            info.namespace= "";
        }
        if(propertyIndex==32)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "TransportationZoneID";
            info.namespace= "";
        }
        if(propertyIndex==33)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "RegionalStructureElementGroupCode";
            info.namespace= "";
        }
        if(propertyIndex==34)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "RegionalStructureAddressConsistencyStatusCode";
            info.namespace= "";
        }
        if(propertyIndex==35)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "RegionalStructureCityCode";
            info.namespace= "";
        }
        if(propertyIndex==36)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "AdditionalRegionalStructureCityCode";
            info.namespace= "";
        }
        if(propertyIndex==37)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "POBoxDeviatingRegionalStructureCityCode";
            info.namespace= "";
        }
        if(propertyIndex==38)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "RegionalStructureDistrictCode";
            info.namespace= "";
        }
        if(propertyIndex==39)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "RegionalStructureStreetCode";
            info.namespace= "";
        }
        if(propertyIndex==40)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ExtendedBuildingID";
            info.namespace= "";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }



    @Override
    public int getAttributeCount() {
        return 1;
    }
    
    @Override
    public void getAttributeInfo(int index, AttributeInfo info) {
        if(index==0)
        {
            info.name = "actionCode";
            info.namespace= "";
            if(this.actionCode!=null)
            {
                info.setValue(this.actionCode);
            }
            
        }
    }

    @Override
    public void getAttribute(int i, AttributeInfo attributeInfo) {

    }

    @Override
    public void setAttribute(AttributeInfo attributeInfo) {

    }    
}

