package com.exampleariba.aribasoup.gerado;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.2.0
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class QBSBusinessDocumentMessageHeader extends AttributeContainer implements KvmSerializable
{

    
    public QBSBusinessDocumentMessageID ID;
    
    public QBSUUID UUID;
    
    public QBSBusinessDocumentMessageID ReferenceID;
    
    public QBSUUID ReferenceUUID;
    
    public java.util.Date CreationDateTime;
    
    public Boolean TestDataIndicator;
    
    public Boolean ReconciliationIndicator;
    
    public String SenderBusinessSystemID;
    
    public String RecipientBusinessSystemID;
    
    public QBSBusinessDocumentMessageHeaderParty SenderParty;
    
    public QBSBusinessDocumentMessageHeaderParty RecipientParty;
    
    public QBSBusinessScope BusinessScope;
    
    public Boolean BusinessDocumentObjectListCompleteTransmissionIndicator=false;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,QBSExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }
        if (inObj.hasAttribute("BusinessDocumentObjectListCompleteTransmissionIndicator"))
        {	
            java.lang.Object j = inObj.getAttribute("BusinessDocumentObjectListCompleteTransmissionIndicator");
            if (j != null)
            {
                BusinessDocumentObjectListCompleteTransmissionIndicator = new Boolean(j.toString());
            }
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,QBSExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("ID"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.ID = (QBSBusinessDocumentMessageID)__envelope.get(j,QBSBusinessDocumentMessageID.class,false);
            }
            return true;
        }
        if (info.name.equals("UUID"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.UUID = (QBSUUID)__envelope.get(j,QBSUUID.class,false);
            }
            return true;
        }
        if (info.name.equals("ReferenceID"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.ReferenceID = (QBSBusinessDocumentMessageID)__envelope.get(j,QBSBusinessDocumentMessageID.class,false);
            }
            return true;
        }
        if (info.name.equals("ReferenceUUID"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.ReferenceUUID = (QBSUUID)__envelope.get(j,QBSUUID.class,false);
            }
            return true;
        }
        if (info.name.equals("CreationDateTime"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.CreationDateTime = QBSHelper.ConvertFromWebService(j.toString());
                    }
                }
                else if (obj instanceof java.util.Date){
                    this.CreationDateTime = (java.util.Date)obj;
                }
            }
            return true;
        }
        if (info.name.equals("TestDataIndicator"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.TestDataIndicator = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.TestDataIndicator = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ReconciliationIndicator"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ReconciliationIndicator = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.ReconciliationIndicator = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("SenderBusinessSystemID"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.SenderBusinessSystemID = j.toString();
                    }
                }
                else{
                    this.SenderBusinessSystemID = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("RecipientBusinessSystemID"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.RecipientBusinessSystemID = j.toString();
                    }
                }
                else{
                    this.RecipientBusinessSystemID = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("SenderParty"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.SenderParty = (QBSBusinessDocumentMessageHeaderParty)__envelope.get(j,QBSBusinessDocumentMessageHeaderParty.class,false);
            }
            return true;
        }
        if (info.name.equals("RecipientParty"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.RecipientParty = (QBSBusinessDocumentMessageHeaderParty)__envelope.get(j,QBSBusinessDocumentMessageHeaderParty.class,false);
            }
            return true;
        }
        if (info.name.equals("BusinessScope"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.BusinessScope = (QBSBusinessScope)__envelope.get(j,QBSBusinessScope.class,false);
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.ID!=null?this.ID.getSimpleValue():null;
        }
        if(propertyIndex==1)
        {
            return this.UUID!=null?this.UUID.getSimpleValue():null;
        }
        if(propertyIndex==2)
        {
            return this.ReferenceID!=null?this.ReferenceID.getSimpleValue():null;
        }
        if(propertyIndex==3)
        {
            return this.ReferenceUUID!=null?this.ReferenceUUID.getSimpleValue():null;
        }
        if(propertyIndex==4)
        {
            return this.CreationDateTime!=null?QBSHelper.getDateTimeFormat().format(this.CreationDateTime):SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.TestDataIndicator!=null?this.TestDataIndicator:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.ReconciliationIndicator!=null?this.ReconciliationIndicator:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==7)
        {
            return this.SenderBusinessSystemID!=null?this.SenderBusinessSystemID:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==8)
        {
            return this.RecipientBusinessSystemID!=null?this.RecipientBusinessSystemID:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==9)
        {
            return this.SenderParty!=null?this.SenderParty:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==10)
        {
            return this.RecipientParty!=null?this.RecipientParty:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==11)
        {
            return this.BusinessScope!=null?this.BusinessScope:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 12;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "ID";
            info.namespace= "";
        }
        if(propertyIndex==1)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "UUID";
            info.namespace= "";
        }
        if(propertyIndex==2)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "ReferenceID";
            info.namespace= "";
        }
        if(propertyIndex==3)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "ReferenceUUID";
            info.namespace= "";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "CreationDateTime";
            info.namespace= "";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "TestDataIndicator";
            info.namespace= "";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "ReconciliationIndicator";
            info.namespace= "";
        }
        if(propertyIndex==7)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "SenderBusinessSystemID";
            info.namespace= "";
        }
        if(propertyIndex==8)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "RecipientBusinessSystemID";
            info.namespace= "";
        }
        if(propertyIndex==9)
        {
            info.type = QBSBusinessDocumentMessageHeaderParty.class;
            info.name = "SenderParty";
            info.namespace= "";
        }
        if(propertyIndex==10)
        {
            info.type = QBSBusinessDocumentMessageHeaderParty.class;
            info.name = "RecipientParty";
            info.namespace= "";
        }
        if(propertyIndex==11)
        {
            info.type = QBSBusinessScope.class;
            info.name = "BusinessScope";
            info.namespace= "";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }



    @Override
    public int getAttributeCount() {
        return 1;
    }
    
    @Override
    public void getAttributeInfo(int index, AttributeInfo info) {
        if(index==0)
        {
            info.name = "BusinessDocumentObjectListCompleteTransmissionIndicator";
            info.namespace= "";
            if(this.BusinessDocumentObjectListCompleteTransmissionIndicator!=null)
            {
                info.setValue(this.BusinessDocumentObjectListCompleteTransmissionIndicator);
            }
            
        }
    }

    @Override
    public void getAttribute(int i, AttributeInfo attributeInfo) {

    }

    @Override
    public void setAttribute(AttributeInfo attributeInfo) {

    }    
}

