package com.exampleariba.aribasoup.gerado;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.2.0
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class QBSBPSUITERplctReqTxNo extends AttributeContainer implements KvmSerializable
{

    
    public String CountryCode;
    
    public QBSTaxIdentificationNumberTypeCode TaxIdentificationNumberTypeCode;
    
    public QBSPartyTaxID PartyTaxID;
    
    public QBSLONG_PartyTaxID LONG_PartyTaxID;
    
    public String actionCode;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,QBSExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }
        if (inObj.hasAttribute("actionCode"))
        {	
            java.lang.Object j = inObj.getAttribute("actionCode");
            if (j != null)
            {
                actionCode = j.toString();
            }
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,QBSExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("CountryCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.CountryCode = j.toString();
                    }
                }
                else{
                    this.CountryCode = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("TaxIdentificationNumberTypeCode"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.TaxIdentificationNumberTypeCode = (QBSTaxIdentificationNumberTypeCode)__envelope.get(j,QBSTaxIdentificationNumberTypeCode.class,false);
            }
            return true;
        }
        if (info.name.equals("PartyTaxID"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.PartyTaxID = (QBSPartyTaxID)__envelope.get(j,QBSPartyTaxID.class,false);
            }
            return true;
        }
        if (info.name.equals("LONG_PartyTaxID"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.LONG_PartyTaxID = (QBSLONG_PartyTaxID)__envelope.get(j,QBSLONG_PartyTaxID.class,false);
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return CountryCode;
        }
        if(propertyIndex==1)
        {
            return this.TaxIdentificationNumberTypeCode!=null?this.TaxIdentificationNumberTypeCode.getSimpleValue():null;
        }
        if(propertyIndex==2)
        {
            return this.PartyTaxID!=null?this.PartyTaxID.getSimpleValue():null;
        }
        if(propertyIndex==3)
        {
            return this.LONG_PartyTaxID!=null?this.LONG_PartyTaxID.getSimpleValue():null;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 4;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "CountryCode";
            info.namespace= "";
        }
        if(propertyIndex==1)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "TaxIdentificationNumberTypeCode";
            info.namespace= "";
        }
        if(propertyIndex==2)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "PartyTaxID";
            info.namespace= "";
        }
        if(propertyIndex==3)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "LONG_PartyTaxID";
            info.namespace= "";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }



    @Override
    public int getAttributeCount() {
        return 1;
    }
    
    @Override
    public void getAttributeInfo(int index, AttributeInfo info) {
        if(index==0)
        {
            info.name = "actionCode";
            info.namespace= "";
            if(this.actionCode!=null)
            {
                info.setValue(this.actionCode);
            }
            
        }
    }

    @Override
    public void getAttribute(int i, AttributeInfo attributeInfo) {

    }

    @Override
    public void setAttribute(AttributeInfo attributeInfo) {

    }    
}

