package com.exampleariba.aribasoup.gerado;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.2.0
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.util.ArrayList;
import org.ksoap2.serialization.PropertyInfo;

public class QBSBPSUITEBulkRplctConfMsg extends AttributeContainer implements KvmSerializable
{

    
    public QBSBusinessDocumentMessageHeader MessageHeader;
    
    public ArrayList< QBSBPSUITERplctConfMsg> BusinessPartnerSUITEReplicateConfirmationMessage =new ArrayList<QBSBPSUITERplctConfMsg >();
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,QBSExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,QBSExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("MessageHeader"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.MessageHeader = (QBSBusinessDocumentMessageHeader)__envelope.get(j,QBSBusinessDocumentMessageHeader.class,false);
            }
            return true;
        }
        if (info.name.equals("BusinessPartnerSUITEReplicateConfirmationMessage"))
        {
            if(obj!=null)
            {
                if(this.BusinessPartnerSUITEReplicateConfirmationMessage==null)
                {
                    this.BusinessPartnerSUITEReplicateConfirmationMessage = new java.util.ArrayList< QBSBPSUITERplctConfMsg>();
                }
                java.lang.Object j =obj;
                QBSBPSUITERplctConfMsg j1= (QBSBPSUITERplctConfMsg)__envelope.get(j,QBSBPSUITERplctConfMsg.class,false);
                this.BusinessPartnerSUITEReplicateConfirmationMessage.add(j1);
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return MessageHeader;
        }
        if(propertyIndex>=1 && propertyIndex < 1+this.BusinessPartnerSUITEReplicateConfirmationMessage.size())
        {
            java.lang.Object BusinessPartnerSUITEReplicateConfirmationMessage = this.BusinessPartnerSUITEReplicateConfirmationMessage.get(propertyIndex-(1));
            return BusinessPartnerSUITEReplicateConfirmationMessage!=null?BusinessPartnerSUITEReplicateConfirmationMessage:SoapPrimitive.NullNilElement;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 1+BusinessPartnerSUITEReplicateConfirmationMessage.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = QBSBusinessDocumentMessageHeader.class;
            info.name = "MessageHeader";
            info.namespace= "";
        }
        if(propertyIndex>=1 && propertyIndex < 1+this.BusinessPartnerSUITEReplicateConfirmationMessage.size())
        {
            info.type = QBSBPSUITERplctConfMsg.class;
            info.name = "BusinessPartnerSUITEReplicateConfirmationMessage";
            info.namespace= "";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

