package com.exampleariba.aribasoup.gerado;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.2.0
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.util.ArrayList;
import org.ksoap2.serialization.PropertyInfo;

public class QBSBPSUITERplctReqText extends AttributeContainer implements KvmSerializable
{

    
    public QBSTextCollectionTextTypeCode TextTypeCode;
    
    public String LanguageCode;
    
    public ArrayList< QBSBPSUITERplctReqTextSAPScriptLine> TextSAPScriptLine =new ArrayList<QBSBPSUITERplctReqTextSAPScriptLine >();
    
    public String actionCode;
    
    public Boolean textSAPScriptLineListCompleteTransmissionIndicator=false;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,QBSExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }
        if (inObj.hasAttribute("actionCode"))
        {	
            java.lang.Object j = inObj.getAttribute("actionCode");
            if (j != null)
            {
                actionCode = j.toString();
            }
        }
        if (inObj.hasAttribute("textSAPScriptLineListCompleteTransmissionIndicator"))
        {	
            java.lang.Object j = inObj.getAttribute("textSAPScriptLineListCompleteTransmissionIndicator");
            if (j != null)
            {
                textSAPScriptLineListCompleteTransmissionIndicator = new Boolean(j.toString());
            }
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,QBSExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("TextTypeCode"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.TextTypeCode = (QBSTextCollectionTextTypeCode)__envelope.get(j,QBSTextCollectionTextTypeCode.class,false);
            }
            return true;
        }
        if (info.name.equals("LanguageCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.LanguageCode = j.toString();
                    }
                }
                else{
                    this.LanguageCode = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("TextSAPScriptLine"))
        {
            if(obj!=null)
            {
                if(this.TextSAPScriptLine==null)
                {
                    this.TextSAPScriptLine = new java.util.ArrayList< QBSBPSUITERplctReqTextSAPScriptLine>();
                }
                java.lang.Object j =obj;
                QBSBPSUITERplctReqTextSAPScriptLine j1= (QBSBPSUITERplctReqTextSAPScriptLine)__envelope.get(j,QBSBPSUITERplctReqTextSAPScriptLine.class,false);
                this.TextSAPScriptLine.add(j1);
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.TextTypeCode!=null?this.TextTypeCode.getSimpleValue():null;
        }
        if(propertyIndex==1)
        {
            return LanguageCode;
        }
        if(propertyIndex>=2 && propertyIndex < 2+this.TextSAPScriptLine.size())
        {
            java.lang.Object TextSAPScriptLine = this.TextSAPScriptLine.get(propertyIndex-(2));
            return TextSAPScriptLine!=null?TextSAPScriptLine:SoapPrimitive.NullNilElement;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 2+TextSAPScriptLine.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "TextTypeCode";
            info.namespace= "";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "LanguageCode";
            info.namespace= "";
        }
        if(propertyIndex>=2 && propertyIndex < 2+this.TextSAPScriptLine.size())
        {
            info.type = QBSBPSUITERplctReqTextSAPScriptLine.class;
            info.name = "TextSAPScriptLine";
            info.namespace= "";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }



    @Override
    public int getAttributeCount() {
        return 2;
    }
    
    @Override
    public void getAttributeInfo(int index, AttributeInfo info) {
        if(index==0)
        {
            info.name = "actionCode";
            info.namespace= "";
            if(this.actionCode!=null)
            {
                info.setValue(this.actionCode);
            }
            
        }
        if(index==1)
        {
            info.name = "textSAPScriptLineListCompleteTransmissionIndicator";
            info.namespace= "";
            if(this.textSAPScriptLineListCompleteTransmissionIndicator!=null)
            {
                info.setValue(this.textSAPScriptLineListCompleteTransmissionIndicator);
            }
            
        }
    }

    @Override
    public void getAttribute(int i, AttributeInfo attributeInfo) {

    }

    @Override
    public void setAttribute(AttributeInfo attributeInfo) {

    }    
}

