package com.exampleariba.aribasoup.gerado;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.2.0
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class QBSBPSUITERplctReqBusHrs extends AttributeContainer implements KvmSerializable
{

    
    public QBSWorkingDayCalendarCode FactoryCalenderCode;
    
    public String TimeZoneCode;
    
    public String MondayAMStartTime;
    
    public String MondayAMEndTime;
    
    public String MondayPMStartTime;
    
    public String MondayPMEndTime;
    
    public String TuesdayAMStartTime;
    
    public String TuesdayAMEndTime;
    
    public String TuesdayPMStartTime;
    
    public String TuesdayPMEndTime;
    
    public String WednesdayAMStartTime;
    
    public String WednesdayAMEndTime;
    
    public String WednesdayPMStartTime;
    
    public String WednesdayPMEndTime;
    
    public String ThursdayAMStartTime;
    
    public String ThursdayAMEndTime;
    
    public String ThursdayPMStartTime;
    
    public String ThursdayPMEndTime;
    
    public String FridayAMStartTime;
    
    public String FridayAMEndTime;
    
    public String FridayPMStartTime;
    
    public String FridayPMEndTime;
    
    public String SaturdayAMStartTime;
    
    public String SaturdayAMEndTime;
    
    public String SaturdayPMStartTime;
    
    public String SaturdayPMEndTime;
    
    public String SundayAMStartTime;
    
    public String SundayAMEndTime;
    
    public String SundayPMStartTime;
    
    public String SundayPMEndTime;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,QBSExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,QBSExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("FactoryCalenderCode"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.FactoryCalenderCode = (QBSWorkingDayCalendarCode)__envelope.get(j,QBSWorkingDayCalendarCode.class,false);
            }
            return true;
        }
        if (info.name.equals("TimeZoneCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.TimeZoneCode = j.toString();
                    }
                }
                else{
                    this.TimeZoneCode = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("MondayAMStartTime"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.MondayAMStartTime = j.toString();
                    }
                }
                else{
                    this.MondayAMStartTime = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("MondayAMEndTime"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.MondayAMEndTime = j.toString();
                    }
                }
                else{
                    this.MondayAMEndTime = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("MondayPMStartTime"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.MondayPMStartTime = j.toString();
                    }
                }
                else{
                    this.MondayPMStartTime = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("MondayPMEndTime"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.MondayPMEndTime = j.toString();
                    }
                }
                else{
                    this.MondayPMEndTime = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("TuesdayAMStartTime"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.TuesdayAMStartTime = j.toString();
                    }
                }
                else{
                    this.TuesdayAMStartTime = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("TuesdayAMEndTime"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.TuesdayAMEndTime = j.toString();
                    }
                }
                else{
                    this.TuesdayAMEndTime = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("TuesdayPMStartTime"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.TuesdayPMStartTime = j.toString();
                    }
                }
                else{
                    this.TuesdayPMStartTime = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("TuesdayPMEndTime"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.TuesdayPMEndTime = j.toString();
                    }
                }
                else{
                    this.TuesdayPMEndTime = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("WednesdayAMStartTime"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.WednesdayAMStartTime = j.toString();
                    }
                }
                else{
                    this.WednesdayAMStartTime = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("WednesdayAMEndTime"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.WednesdayAMEndTime = j.toString();
                    }
                }
                else{
                    this.WednesdayAMEndTime = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("WednesdayPMStartTime"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.WednesdayPMStartTime = j.toString();
                    }
                }
                else{
                    this.WednesdayPMStartTime = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("WednesdayPMEndTime"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.WednesdayPMEndTime = j.toString();
                    }
                }
                else{
                    this.WednesdayPMEndTime = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("ThursdayAMStartTime"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ThursdayAMStartTime = j.toString();
                    }
                }
                else{
                    this.ThursdayAMStartTime = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("ThursdayAMEndTime"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ThursdayAMEndTime = j.toString();
                    }
                }
                else{
                    this.ThursdayAMEndTime = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("ThursdayPMStartTime"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ThursdayPMStartTime = j.toString();
                    }
                }
                else{
                    this.ThursdayPMStartTime = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("ThursdayPMEndTime"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ThursdayPMEndTime = j.toString();
                    }
                }
                else{
                    this.ThursdayPMEndTime = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("FridayAMStartTime"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.FridayAMStartTime = j.toString();
                    }
                }
                else{
                    this.FridayAMStartTime = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("FridayAMEndTime"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.FridayAMEndTime = j.toString();
                    }
                }
                else{
                    this.FridayAMEndTime = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("FridayPMStartTime"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.FridayPMStartTime = j.toString();
                    }
                }
                else{
                    this.FridayPMStartTime = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("FridayPMEndTime"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.FridayPMEndTime = j.toString();
                    }
                }
                else{
                    this.FridayPMEndTime = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("SaturdayAMStartTime"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.SaturdayAMStartTime = j.toString();
                    }
                }
                else{
                    this.SaturdayAMStartTime = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("SaturdayAMEndTime"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.SaturdayAMEndTime = j.toString();
                    }
                }
                else{
                    this.SaturdayAMEndTime = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("SaturdayPMStartTime"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.SaturdayPMStartTime = j.toString();
                    }
                }
                else{
                    this.SaturdayPMStartTime = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("SaturdayPMEndTime"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.SaturdayPMEndTime = j.toString();
                    }
                }
                else{
                    this.SaturdayPMEndTime = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("SundayAMStartTime"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.SundayAMStartTime = j.toString();
                    }
                }
                else{
                    this.SundayAMStartTime = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("SundayAMEndTime"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.SundayAMEndTime = j.toString();
                    }
                }
                else{
                    this.SundayAMEndTime = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("SundayPMStartTime"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.SundayPMStartTime = j.toString();
                    }
                }
                else{
                    this.SundayPMStartTime = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("SundayPMEndTime"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.SundayPMEndTime = j.toString();
                    }
                }
                else{
                    this.SundayPMEndTime = obj.toString();
                }
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.FactoryCalenderCode!=null?this.FactoryCalenderCode.getSimpleValue():null;
        }
        if(propertyIndex==1)
        {
            return this.TimeZoneCode!=null?this.TimeZoneCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.MondayAMStartTime!=null?this.MondayAMStartTime:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.MondayAMEndTime!=null?this.MondayAMEndTime:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.MondayPMStartTime!=null?this.MondayPMStartTime:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.MondayPMEndTime!=null?this.MondayPMEndTime:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.TuesdayAMStartTime!=null?this.TuesdayAMStartTime:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==7)
        {
            return this.TuesdayAMEndTime!=null?this.TuesdayAMEndTime:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==8)
        {
            return this.TuesdayPMStartTime!=null?this.TuesdayPMStartTime:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==9)
        {
            return this.TuesdayPMEndTime!=null?this.TuesdayPMEndTime:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==10)
        {
            return this.WednesdayAMStartTime!=null?this.WednesdayAMStartTime:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==11)
        {
            return this.WednesdayAMEndTime!=null?this.WednesdayAMEndTime:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==12)
        {
            return this.WednesdayPMStartTime!=null?this.WednesdayPMStartTime:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==13)
        {
            return this.WednesdayPMEndTime!=null?this.WednesdayPMEndTime:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==14)
        {
            return this.ThursdayAMStartTime!=null?this.ThursdayAMStartTime:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==15)
        {
            return this.ThursdayAMEndTime!=null?this.ThursdayAMEndTime:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==16)
        {
            return this.ThursdayPMStartTime!=null?this.ThursdayPMStartTime:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==17)
        {
            return this.ThursdayPMEndTime!=null?this.ThursdayPMEndTime:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==18)
        {
            return this.FridayAMStartTime!=null?this.FridayAMStartTime:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==19)
        {
            return this.FridayAMEndTime!=null?this.FridayAMEndTime:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==20)
        {
            return this.FridayPMStartTime!=null?this.FridayPMStartTime:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==21)
        {
            return this.FridayPMEndTime!=null?this.FridayPMEndTime:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==22)
        {
            return this.SaturdayAMStartTime!=null?this.SaturdayAMStartTime:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==23)
        {
            return this.SaturdayAMEndTime!=null?this.SaturdayAMEndTime:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==24)
        {
            return this.SaturdayPMStartTime!=null?this.SaturdayPMStartTime:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==25)
        {
            return this.SaturdayPMEndTime!=null?this.SaturdayPMEndTime:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==26)
        {
            return this.SundayAMStartTime!=null?this.SundayAMStartTime:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==27)
        {
            return this.SundayAMEndTime!=null?this.SundayAMEndTime:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==28)
        {
            return this.SundayPMStartTime!=null?this.SundayPMStartTime:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==29)
        {
            return this.SundayPMEndTime!=null?this.SundayPMEndTime:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 30;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "FactoryCalenderCode";
            info.namespace= "";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "TimeZoneCode";
            info.namespace= "";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "MondayAMStartTime";
            info.namespace= "";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "MondayAMEndTime";
            info.namespace= "";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "MondayPMStartTime";
            info.namespace= "";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "MondayPMEndTime";
            info.namespace= "";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "TuesdayAMStartTime";
            info.namespace= "";
        }
        if(propertyIndex==7)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "TuesdayAMEndTime";
            info.namespace= "";
        }
        if(propertyIndex==8)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "TuesdayPMStartTime";
            info.namespace= "";
        }
        if(propertyIndex==9)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "TuesdayPMEndTime";
            info.namespace= "";
        }
        if(propertyIndex==10)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "WednesdayAMStartTime";
            info.namespace= "";
        }
        if(propertyIndex==11)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "WednesdayAMEndTime";
            info.namespace= "";
        }
        if(propertyIndex==12)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "WednesdayPMStartTime";
            info.namespace= "";
        }
        if(propertyIndex==13)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "WednesdayPMEndTime";
            info.namespace= "";
        }
        if(propertyIndex==14)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ThursdayAMStartTime";
            info.namespace= "";
        }
        if(propertyIndex==15)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ThursdayAMEndTime";
            info.namespace= "";
        }
        if(propertyIndex==16)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ThursdayPMStartTime";
            info.namespace= "";
        }
        if(propertyIndex==17)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ThursdayPMEndTime";
            info.namespace= "";
        }
        if(propertyIndex==18)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "FridayAMStartTime";
            info.namespace= "";
        }
        if(propertyIndex==19)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "FridayAMEndTime";
            info.namespace= "";
        }
        if(propertyIndex==20)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "FridayPMStartTime";
            info.namespace= "";
        }
        if(propertyIndex==21)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "FridayPMEndTime";
            info.namespace= "";
        }
        if(propertyIndex==22)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "SaturdayAMStartTime";
            info.namespace= "";
        }
        if(propertyIndex==23)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "SaturdayAMEndTime";
            info.namespace= "";
        }
        if(propertyIndex==24)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "SaturdayPMStartTime";
            info.namespace= "";
        }
        if(propertyIndex==25)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "SaturdayPMEndTime";
            info.namespace= "";
        }
        if(propertyIndex==26)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "SundayAMStartTime";
            info.namespace= "";
        }
        if(propertyIndex==27)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "SundayAMEndTime";
            info.namespace= "";
        }
        if(propertyIndex==28)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "SundayPMStartTime";
            info.namespace= "";
        }
        if(propertyIndex==29)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "SundayPMEndTime";
            info.namespace= "";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

