package com.exampleariba.aribasoup.gerado;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.2.0
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.util.ArrayList;
import org.ksoap2.serialization.PropertyInfo;

public class QBSBPSUITERplctReqSuplr extends AttributeContainer implements KvmSerializable
{

    
    public String InternalID;
    
    public String ReceiverInternalID;
    
    public String CreditorInformationNumber;
    
    public QBSBusinessPartnerMaintenanceProfileCode MaintenanceProfileCode;
    
    public QBSSupplierProcurementTransactionBlockingCode ProcurementTransactionBlockingCode;
    
    public Boolean DeletionBlockedIndicator;
    
    public Boolean DeletedIndicator;
    
    public Boolean PostingBlockedIndicator;
    
    public Boolean PurchasingBlockedIndicator;
    
    public QBSCompanyID TradingPartnerCompanyID;
    
    public String ManufacturerPartyID;
    
    public QBSAuthorisationGroupCode AuthorisationGroupCode;
    
    public String CorporateGroupName;
    
    public String ProofOfDeliveryRequirementCode;
    
    public java.util.Date CreditDataLastCheckDate;
    
    public String TrainStationLocationName;
    
    public QBSCode DataMediumExchangeReportCode;
    
    public QBSCode DataMediumExchangeInstructionCode;
    
    public QBSIdentifier InpaymentSlipWithReferenceNumberSubscriberID;
    
    public QBSPartyInternalID AlternativePayeePartyInternalID;
    
    public QBSPartyInternalID ReceiverAlternativePayeePartyInternalID;
    
    public Boolean AlternativePayeeAllowedIndicator;
    
    public Boolean EqualizationTaxRelevanceIndicator;
    
    public Boolean ValueAddedTaxRelevanceIndicator;
    
    public QBSPartyInternalID FiscalAddressPartyInternalID;
    
    public QBSPartyInternalID ReceiverFiscalAddressPartyInternalID;
    
    public QBSPlantID SupplyingPlantID;
    
    public Boolean SellerAssortmentProductGroupLevelRelevanceIndicator;
    
    public Boolean PlantLevelRelevanceIndicator;
    
    public QBSWorkingDayCalendarCode WorkingDayCalendarCode;
    
    public QBSPartyStandardID CarrierPartyStandardID;
    
    public QBSCode CarrierPartyFreightGroupCode;
    
    public QBSCode ServicePerformerPartyGroupCode;
    
    public QBSCode StatisticsGroupCode;
    
    public String TaxAuthorityPartyID;
    
    public QBSCode TaxGroupCode;
    
    public QBSCode SocialInsuranceActivityCode;
    
    public Boolean ForSocialInsuranceRegisteredIndicator;
    
    public Boolean TaxSplitIndicator;
    
    public QBSCode TaxBasePercentageCode;
    
    public QBSPartyInternalID ResponsibleTaxOfficePartyInternalID;
    
    public QBSPartyInternalID ReceiverResponsibleTaxOfficePartyInternalID;
    
    public String RepresentativeName;
    
    public String BusinessTypeName;
    
    public String IndustryTypeName;
    
    public String RelatedCustomerInternalID;
    
    public String ReceiverRelatedCustomerInternalID;
    
    public ArrayList< QBSBPSUITERplctReqAcctgInfo> AccountingInformation =new ArrayList<QBSBPSUITERplctReqAcctgInfo >();
    
    public QBSBPSUITERplctReqBiddingCharc BiddingCharacteristic;
    
    public ArrayList< QBSBPSUITERplctReqProcmtCardIssuingInstitutes> ProcurementCardIssuingInstitutes =new ArrayList<QBSBPSUITERplctReqProcmtCardIssuingInstitutes >();
    
    public ArrayList< QBSBPSUITERplctReqQltyMgmt> QualityManagement =new ArrayList<QBSBPSUITERplctReqQltyMgmt >();
    
    public ArrayList< QBSBPSUITERplctReqProcmtArrgmt> ProcurementArrangement =new ArrayList<QBSBPSUITERplctReqProcmtArrgmt >();
    
    public ArrayList< QBSBPSUITERplctReqSubRnge> SubRange =new ArrayList<QBSBPSUITERplctReqSubRnge >();
    
    public ArrayList< QBSBPSUITERplctReqTxGrpg> TaxGrouping =new ArrayList<QBSBPSUITERplctReqTxGrpg >();
    
    public ArrayList< QBSBPSUITERplctReqText> SupplierText =new ArrayList<QBSBPSUITERplctReqText >();
    
    public ArrayList< QBSBPSUITERplctReqDoc> SupplierDocument =new ArrayList<QBSBPSUITERplctReqDoc >();
    
    public ArrayList< QBSGenericCustomField> GenericCustomField =new ArrayList<QBSGenericCustomField >();
    
    public Boolean accountingInformationListCompleteTransmissionIndicator=false;
    
    public Boolean biddingCharacteristicListCompleteTransmissionIndicator=false;
    
    public Boolean procurementCardIssuingInstitutesListCompleteTransmissionIndicator=false;
    
    public Boolean qualitiyManagementListCompleteTransmissionIndicator=false;
    
    public Boolean procurementArrangementListCompleteTransmissionIndicator=false;
    
    public Boolean subRangeListCompleteTransmissionIndicator=false;
    
    public Boolean taxGroupingListCompleteTransmissionIndicator=false;
    
    public Boolean supplierTextListCompleteTransmissionIndicator=false;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,QBSExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }
        if (inObj.hasAttribute("accountingInformationListCompleteTransmissionIndicator"))
        {	
            java.lang.Object j = inObj.getAttribute("accountingInformationListCompleteTransmissionIndicator");
            if (j != null)
            {
                accountingInformationListCompleteTransmissionIndicator = new Boolean(j.toString());
            }
        }
        if (inObj.hasAttribute("biddingCharacteristicListCompleteTransmissionIndicator"))
        {	
            java.lang.Object j = inObj.getAttribute("biddingCharacteristicListCompleteTransmissionIndicator");
            if (j != null)
            {
                biddingCharacteristicListCompleteTransmissionIndicator = new Boolean(j.toString());
            }
        }
        if (inObj.hasAttribute("procurementCardIssuingInstitutesListCompleteTransmissionIndicator"))
        {	
            java.lang.Object j = inObj.getAttribute("procurementCardIssuingInstitutesListCompleteTransmissionIndicator");
            if (j != null)
            {
                procurementCardIssuingInstitutesListCompleteTransmissionIndicator = new Boolean(j.toString());
            }
        }
        if (inObj.hasAttribute("qualitiyManagementListCompleteTransmissionIndicator"))
        {	
            java.lang.Object j = inObj.getAttribute("qualitiyManagementListCompleteTransmissionIndicator");
            if (j != null)
            {
                qualitiyManagementListCompleteTransmissionIndicator = new Boolean(j.toString());
            }
        }
        if (inObj.hasAttribute("procurementArrangementListCompleteTransmissionIndicator"))
        {	
            java.lang.Object j = inObj.getAttribute("procurementArrangementListCompleteTransmissionIndicator");
            if (j != null)
            {
                procurementArrangementListCompleteTransmissionIndicator = new Boolean(j.toString());
            }
        }
        if (inObj.hasAttribute("subRangeListCompleteTransmissionIndicator"))
        {	
            java.lang.Object j = inObj.getAttribute("subRangeListCompleteTransmissionIndicator");
            if (j != null)
            {
                subRangeListCompleteTransmissionIndicator = new Boolean(j.toString());
            }
        }
        if (inObj.hasAttribute("taxGroupingListCompleteTransmissionIndicator"))
        {	
            java.lang.Object j = inObj.getAttribute("taxGroupingListCompleteTransmissionIndicator");
            if (j != null)
            {
                taxGroupingListCompleteTransmissionIndicator = new Boolean(j.toString());
            }
        }
        if (inObj.hasAttribute("supplierTextListCompleteTransmissionIndicator"))
        {	
            java.lang.Object j = inObj.getAttribute("supplierTextListCompleteTransmissionIndicator");
            if (j != null)
            {
                supplierTextListCompleteTransmissionIndicator = new Boolean(j.toString());
            }
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,QBSExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("InternalID"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.InternalID = j.toString();
                    }
                }
                else{
                    this.InternalID = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("ReceiverInternalID"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ReceiverInternalID = j.toString();
                    }
                }
                else{
                    this.ReceiverInternalID = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("CreditorInformationNumber"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.CreditorInformationNumber = j.toString();
                    }
                }
                else{
                    this.CreditorInformationNumber = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("MaintenanceProfileCode"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.MaintenanceProfileCode = (QBSBusinessPartnerMaintenanceProfileCode)__envelope.get(j,QBSBusinessPartnerMaintenanceProfileCode.class,false);
            }
            return true;
        }
        if (info.name.equals("ProcurementTransactionBlockingCode"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.ProcurementTransactionBlockingCode = (QBSSupplierProcurementTransactionBlockingCode)__envelope.get(j,QBSSupplierProcurementTransactionBlockingCode.class,false);
            }
            return true;
        }
        if (info.name.equals("DeletionBlockedIndicator"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.DeletionBlockedIndicator = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.DeletionBlockedIndicator = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("DeletedIndicator"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.DeletedIndicator = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.DeletedIndicator = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("PostingBlockedIndicator"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.PostingBlockedIndicator = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.PostingBlockedIndicator = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("PurchasingBlockedIndicator"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.PurchasingBlockedIndicator = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.PurchasingBlockedIndicator = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("TradingPartnerCompanyID"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.TradingPartnerCompanyID = (QBSCompanyID)__envelope.get(j,QBSCompanyID.class,false);
            }
            return true;
        }
        if (info.name.equals("ManufacturerPartyID"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ManufacturerPartyID = j.toString();
                    }
                }
                else{
                    this.ManufacturerPartyID = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("AuthorisationGroupCode"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.AuthorisationGroupCode = (QBSAuthorisationGroupCode)__envelope.get(j,QBSAuthorisationGroupCode.class,false);
            }
            return true;
        }
        if (info.name.equals("CorporateGroupName"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.CorporateGroupName = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.CorporateGroupName = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ProofOfDeliveryRequirementCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ProofOfDeliveryRequirementCode = j.toString();
                    }
                }
                else{
                    this.ProofOfDeliveryRequirementCode = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("CreditDataLastCheckDate"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.CreditDataLastCheckDate = QBSHelper.ConvertFromWebService(j.toString());
                    }
                }
                else if (obj instanceof java.util.Date){
                    this.CreditDataLastCheckDate = (java.util.Date)obj;
                }
            }
            return true;
        }
        if (info.name.equals("TrainStationLocationName"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.TrainStationLocationName = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.TrainStationLocationName = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("DataMediumExchangeReportCode"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.DataMediumExchangeReportCode = (QBSCode)__envelope.get(j,QBSCode.class,false);
            }
            return true;
        }
        if (info.name.equals("DataMediumExchangeInstructionCode"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.DataMediumExchangeInstructionCode = (QBSCode)__envelope.get(j,QBSCode.class,false);
            }
            return true;
        }
        if (info.name.equals("InpaymentSlipWithReferenceNumberSubscriberID"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.InpaymentSlipWithReferenceNumberSubscriberID = (QBSIdentifier)__envelope.get(j,QBSIdentifier.class,false);
            }
            return true;
        }
        if (info.name.equals("AlternativePayeePartyInternalID"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.AlternativePayeePartyInternalID = (QBSPartyInternalID)__envelope.get(j,QBSPartyInternalID.class,false);
            }
            return true;
        }
        if (info.name.equals("ReceiverAlternativePayeePartyInternalID"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.ReceiverAlternativePayeePartyInternalID = (QBSPartyInternalID)__envelope.get(j,QBSPartyInternalID.class,false);
            }
            return true;
        }
        if (info.name.equals("AlternativePayeeAllowedIndicator"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.AlternativePayeeAllowedIndicator = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.AlternativePayeeAllowedIndicator = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("EqualizationTaxRelevanceIndicator"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.EqualizationTaxRelevanceIndicator = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.EqualizationTaxRelevanceIndicator = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ValueAddedTaxRelevanceIndicator"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ValueAddedTaxRelevanceIndicator = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.ValueAddedTaxRelevanceIndicator = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("FiscalAddressPartyInternalID"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.FiscalAddressPartyInternalID = (QBSPartyInternalID)__envelope.get(j,QBSPartyInternalID.class,false);
            }
            return true;
        }
        if (info.name.equals("ReceiverFiscalAddressPartyInternalID"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.ReceiverFiscalAddressPartyInternalID = (QBSPartyInternalID)__envelope.get(j,QBSPartyInternalID.class,false);
            }
            return true;
        }
        if (info.name.equals("SupplyingPlantID"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.SupplyingPlantID = (QBSPlantID)__envelope.get(j,QBSPlantID.class,false);
            }
            return true;
        }
        if (info.name.equals("SellerAssortmentProductGroupLevelRelevanceIndicator"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.SellerAssortmentProductGroupLevelRelevanceIndicator = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.SellerAssortmentProductGroupLevelRelevanceIndicator = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("PlantLevelRelevanceIndicator"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.PlantLevelRelevanceIndicator = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.PlantLevelRelevanceIndicator = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("WorkingDayCalendarCode"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.WorkingDayCalendarCode = (QBSWorkingDayCalendarCode)__envelope.get(j,QBSWorkingDayCalendarCode.class,false);
            }
            return true;
        }
        if (info.name.equals("CarrierPartyStandardID"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.CarrierPartyStandardID = (QBSPartyStandardID)__envelope.get(j,QBSPartyStandardID.class,false);
            }
            return true;
        }
        if (info.name.equals("CarrierPartyFreightGroupCode"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.CarrierPartyFreightGroupCode = (QBSCode)__envelope.get(j,QBSCode.class,false);
            }
            return true;
        }
        if (info.name.equals("ServicePerformerPartyGroupCode"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.ServicePerformerPartyGroupCode = (QBSCode)__envelope.get(j,QBSCode.class,false);
            }
            return true;
        }
        if (info.name.equals("StatisticsGroupCode"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.StatisticsGroupCode = (QBSCode)__envelope.get(j,QBSCode.class,false);
            }
            return true;
        }
        if (info.name.equals("TaxAuthorityPartyID"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.TaxAuthorityPartyID = j.toString();
                    }
                }
                else{
                    this.TaxAuthorityPartyID = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("TaxGroupCode"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.TaxGroupCode = (QBSCode)__envelope.get(j,QBSCode.class,false);
            }
            return true;
        }
        if (info.name.equals("SocialInsuranceActivityCode"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.SocialInsuranceActivityCode = (QBSCode)__envelope.get(j,QBSCode.class,false);
            }
            return true;
        }
        if (info.name.equals("ForSocialInsuranceRegisteredIndicator"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ForSocialInsuranceRegisteredIndicator = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.ForSocialInsuranceRegisteredIndicator = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("TaxSplitIndicator"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.TaxSplitIndicator = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.TaxSplitIndicator = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("TaxBasePercentageCode"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.TaxBasePercentageCode = (QBSCode)__envelope.get(j,QBSCode.class,false);
            }
            return true;
        }
        if (info.name.equals("ResponsibleTaxOfficePartyInternalID"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.ResponsibleTaxOfficePartyInternalID = (QBSPartyInternalID)__envelope.get(j,QBSPartyInternalID.class,false);
            }
            return true;
        }
        if (info.name.equals("ReceiverResponsibleTaxOfficePartyInternalID"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.ReceiverResponsibleTaxOfficePartyInternalID = (QBSPartyInternalID)__envelope.get(j,QBSPartyInternalID.class,false);
            }
            return true;
        }
        if (info.name.equals("RepresentativeName"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.RepresentativeName = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.RepresentativeName = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("BusinessTypeName"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.BusinessTypeName = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.BusinessTypeName = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("IndustryTypeName"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.IndustryTypeName = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.IndustryTypeName = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("RelatedCustomerInternalID"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.RelatedCustomerInternalID = j.toString();
                    }
                }
                else{
                    this.RelatedCustomerInternalID = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("ReceiverRelatedCustomerInternalID"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ReceiverRelatedCustomerInternalID = j.toString();
                    }
                }
                else{
                    this.ReceiverRelatedCustomerInternalID = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("AccountingInformation"))
        {
            if(obj!=null)
            {
                if(this.AccountingInformation==null)
                {
                    this.AccountingInformation = new java.util.ArrayList< QBSBPSUITERplctReqAcctgInfo>();
                }
                java.lang.Object j =obj;
                QBSBPSUITERplctReqAcctgInfo j1= (QBSBPSUITERplctReqAcctgInfo)__envelope.get(j,QBSBPSUITERplctReqAcctgInfo.class,false);
                this.AccountingInformation.add(j1);
            }
            return true;
        }
        if (info.name.equals("BiddingCharacteristic"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.BiddingCharacteristic = (QBSBPSUITERplctReqBiddingCharc)__envelope.get(j,QBSBPSUITERplctReqBiddingCharc.class,false);
            }
            return true;
        }
        if (info.name.equals("ProcurementCardIssuingInstitutes"))
        {
            if(obj!=null)
            {
                if(this.ProcurementCardIssuingInstitutes==null)
                {
                    this.ProcurementCardIssuingInstitutes = new java.util.ArrayList< QBSBPSUITERplctReqProcmtCardIssuingInstitutes>();
                }
                java.lang.Object j =obj;
                QBSBPSUITERplctReqProcmtCardIssuingInstitutes j1= (QBSBPSUITERplctReqProcmtCardIssuingInstitutes)__envelope.get(j,QBSBPSUITERplctReqProcmtCardIssuingInstitutes.class,false);
                this.ProcurementCardIssuingInstitutes.add(j1);
            }
            return true;
        }
        if (info.name.equals("QualityManagement"))
        {
            if(obj!=null)
            {
                if(this.QualityManagement==null)
                {
                    this.QualityManagement = new java.util.ArrayList< QBSBPSUITERplctReqQltyMgmt>();
                }
                java.lang.Object j =obj;
                QBSBPSUITERplctReqQltyMgmt j1= (QBSBPSUITERplctReqQltyMgmt)__envelope.get(j,QBSBPSUITERplctReqQltyMgmt.class,false);
                this.QualityManagement.add(j1);
            }
            return true;
        }
        if (info.name.equals("ProcurementArrangement"))
        {
            if(obj!=null)
            {
                if(this.ProcurementArrangement==null)
                {
                    this.ProcurementArrangement = new java.util.ArrayList< QBSBPSUITERplctReqProcmtArrgmt>();
                }
                java.lang.Object j =obj;
                QBSBPSUITERplctReqProcmtArrgmt j1= (QBSBPSUITERplctReqProcmtArrgmt)__envelope.get(j,QBSBPSUITERplctReqProcmtArrgmt.class,false);
                this.ProcurementArrangement.add(j1);
            }
            return true;
        }
        if (info.name.equals("SubRange"))
        {
            if(obj!=null)
            {
                if(this.SubRange==null)
                {
                    this.SubRange = new java.util.ArrayList< QBSBPSUITERplctReqSubRnge>();
                }
                java.lang.Object j =obj;
                QBSBPSUITERplctReqSubRnge j1= (QBSBPSUITERplctReqSubRnge)__envelope.get(j,QBSBPSUITERplctReqSubRnge.class,false);
                this.SubRange.add(j1);
            }
            return true;
        }
        if (info.name.equals("TaxGrouping"))
        {
            if(obj!=null)
            {
                if(this.TaxGrouping==null)
                {
                    this.TaxGrouping = new java.util.ArrayList< QBSBPSUITERplctReqTxGrpg>();
                }
                java.lang.Object j =obj;
                QBSBPSUITERplctReqTxGrpg j1= (QBSBPSUITERplctReqTxGrpg)__envelope.get(j,QBSBPSUITERplctReqTxGrpg.class,false);
                this.TaxGrouping.add(j1);
            }
            return true;
        }
        if (info.name.equals("SupplierText"))
        {
            if(obj!=null)
            {
                if(this.SupplierText==null)
                {
                    this.SupplierText = new java.util.ArrayList< QBSBPSUITERplctReqText>();
                }
                java.lang.Object j =obj;
                QBSBPSUITERplctReqText j1= (QBSBPSUITERplctReqText)__envelope.get(j,QBSBPSUITERplctReqText.class,false);
                this.SupplierText.add(j1);
            }
            return true;
        }
        if (info.name.equals("SupplierDocument"))
        {
            if(obj!=null)
            {
                if(this.SupplierDocument==null)
                {
                    this.SupplierDocument = new java.util.ArrayList< QBSBPSUITERplctReqDoc>();
                }
                java.lang.Object j =obj;
                QBSBPSUITERplctReqDoc j1= (QBSBPSUITERplctReqDoc)__envelope.get(j,QBSBPSUITERplctReqDoc.class,false);
                this.SupplierDocument.add(j1);
            }
            return true;
        }
        if (info.name.equals("GenericCustomField"))
        {
            if(obj!=null)
            {
                if(this.GenericCustomField==null)
                {
                    this.GenericCustomField = new java.util.ArrayList< QBSGenericCustomField>();
                }
                java.lang.Object j =obj;
                QBSGenericCustomField j1= (QBSGenericCustomField)__envelope.get(j,QBSGenericCustomField.class,false);
                this.GenericCustomField.add(j1);
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.InternalID!=null?this.InternalID:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.ReceiverInternalID!=null?this.ReceiverInternalID:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.CreditorInformationNumber!=null?this.CreditorInformationNumber:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.MaintenanceProfileCode!=null?this.MaintenanceProfileCode.getSimpleValue():null;
        }
        if(propertyIndex==4)
        {
            return this.ProcurementTransactionBlockingCode!=null?this.ProcurementTransactionBlockingCode.getSimpleValue():null;
        }
        if(propertyIndex==5)
        {
            return this.DeletionBlockedIndicator!=null?this.DeletionBlockedIndicator:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.DeletedIndicator!=null?this.DeletedIndicator:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==7)
        {
            return this.PostingBlockedIndicator!=null?this.PostingBlockedIndicator:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==8)
        {
            return this.PurchasingBlockedIndicator!=null?this.PurchasingBlockedIndicator:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==9)
        {
            return this.TradingPartnerCompanyID!=null?this.TradingPartnerCompanyID.getSimpleValue():null;
        }
        if(propertyIndex==10)
        {
            return this.ManufacturerPartyID!=null?this.ManufacturerPartyID:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==11)
        {
            return this.AuthorisationGroupCode!=null?this.AuthorisationGroupCode.getSimpleValue():null;
        }
        if(propertyIndex==12)
        {
            return this.CorporateGroupName!=null?this.CorporateGroupName:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==13)
        {
            return this.ProofOfDeliveryRequirementCode!=null?this.ProofOfDeliveryRequirementCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==14)
        {
            return this.CreditDataLastCheckDate!=null?QBSHelper.getDateFormat().format(this.CreditDataLastCheckDate):SoapPrimitive.NullSkip;
        }
        if(propertyIndex==15)
        {
            return this.TrainStationLocationName!=null?this.TrainStationLocationName:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==16)
        {
            return this.DataMediumExchangeReportCode!=null?this.DataMediumExchangeReportCode.getSimpleValue():null;
        }
        if(propertyIndex==17)
        {
            return this.DataMediumExchangeInstructionCode!=null?this.DataMediumExchangeInstructionCode.getSimpleValue():null;
        }
        if(propertyIndex==18)
        {
            return this.InpaymentSlipWithReferenceNumberSubscriberID!=null?this.InpaymentSlipWithReferenceNumberSubscriberID.getSimpleValue():null;
        }
        if(propertyIndex==19)
        {
            return this.AlternativePayeePartyInternalID!=null?this.AlternativePayeePartyInternalID.getSimpleValue():null;
        }
        if(propertyIndex==20)
        {
            return this.ReceiverAlternativePayeePartyInternalID!=null?this.ReceiverAlternativePayeePartyInternalID.getSimpleValue():null;
        }
        if(propertyIndex==21)
        {
            return this.AlternativePayeeAllowedIndicator!=null?this.AlternativePayeeAllowedIndicator:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==22)
        {
            return this.EqualizationTaxRelevanceIndicator!=null?this.EqualizationTaxRelevanceIndicator:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==23)
        {
            return this.ValueAddedTaxRelevanceIndicator!=null?this.ValueAddedTaxRelevanceIndicator:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==24)
        {
            return this.FiscalAddressPartyInternalID!=null?this.FiscalAddressPartyInternalID.getSimpleValue():null;
        }
        if(propertyIndex==25)
        {
            return this.ReceiverFiscalAddressPartyInternalID!=null?this.ReceiverFiscalAddressPartyInternalID.getSimpleValue():null;
        }
        if(propertyIndex==26)
        {
            return this.SupplyingPlantID!=null?this.SupplyingPlantID.getSimpleValue():null;
        }
        if(propertyIndex==27)
        {
            return this.SellerAssortmentProductGroupLevelRelevanceIndicator!=null?this.SellerAssortmentProductGroupLevelRelevanceIndicator:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==28)
        {
            return this.PlantLevelRelevanceIndicator!=null?this.PlantLevelRelevanceIndicator:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==29)
        {
            return this.WorkingDayCalendarCode!=null?this.WorkingDayCalendarCode.getSimpleValue():null;
        }
        if(propertyIndex==30)
        {
            return this.CarrierPartyStandardID!=null?this.CarrierPartyStandardID.getSimpleValue():null;
        }
        if(propertyIndex==31)
        {
            return this.CarrierPartyFreightGroupCode!=null?this.CarrierPartyFreightGroupCode.getSimpleValue():null;
        }
        if(propertyIndex==32)
        {
            return this.ServicePerformerPartyGroupCode!=null?this.ServicePerformerPartyGroupCode.getSimpleValue():null;
        }
        if(propertyIndex==33)
        {
            return this.StatisticsGroupCode!=null?this.StatisticsGroupCode.getSimpleValue():null;
        }
        if(propertyIndex==34)
        {
            return this.TaxAuthorityPartyID!=null?this.TaxAuthorityPartyID:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==35)
        {
            return this.TaxGroupCode!=null?this.TaxGroupCode.getSimpleValue():null;
        }
        if(propertyIndex==36)
        {
            return this.SocialInsuranceActivityCode!=null?this.SocialInsuranceActivityCode.getSimpleValue():null;
        }
        if(propertyIndex==37)
        {
            return this.ForSocialInsuranceRegisteredIndicator!=null?this.ForSocialInsuranceRegisteredIndicator:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==38)
        {
            return this.TaxSplitIndicator!=null?this.TaxSplitIndicator:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==39)
        {
            return this.TaxBasePercentageCode!=null?this.TaxBasePercentageCode.getSimpleValue():null;
        }
        if(propertyIndex==40)
        {
            return this.ResponsibleTaxOfficePartyInternalID!=null?this.ResponsibleTaxOfficePartyInternalID.getSimpleValue():null;
        }
        if(propertyIndex==41)
        {
            return this.ReceiverResponsibleTaxOfficePartyInternalID!=null?this.ReceiverResponsibleTaxOfficePartyInternalID.getSimpleValue():null;
        }
        if(propertyIndex==42)
        {
            return this.RepresentativeName!=null?this.RepresentativeName:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==43)
        {
            return this.BusinessTypeName!=null?this.BusinessTypeName:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==44)
        {
            return this.IndustryTypeName!=null?this.IndustryTypeName:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==45)
        {
            return this.RelatedCustomerInternalID!=null?this.RelatedCustomerInternalID:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==46)
        {
            return this.ReceiverRelatedCustomerInternalID!=null?this.ReceiverRelatedCustomerInternalID:SoapPrimitive.NullSkip;
        }
        if(propertyIndex>=47 && propertyIndex < 47+this.AccountingInformation.size())
        {
            java.lang.Object AccountingInformation = this.AccountingInformation.get(propertyIndex-(47));
            return AccountingInformation!=null?AccountingInformation:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==47+this.AccountingInformation.size())
        {
            return this.BiddingCharacteristic!=null?this.BiddingCharacteristic:SoapPrimitive.NullSkip;
        }
        if(propertyIndex>=48+this.AccountingInformation.size() && propertyIndex < 48+this.AccountingInformation.size()+this.ProcurementCardIssuingInstitutes.size())
        {
            java.lang.Object ProcurementCardIssuingInstitutes = this.ProcurementCardIssuingInstitutes.get(propertyIndex-(48+this.AccountingInformation.size()));
            return ProcurementCardIssuingInstitutes!=null?ProcurementCardIssuingInstitutes:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex>=48+this.AccountingInformation.size()+this.ProcurementCardIssuingInstitutes.size() && propertyIndex < 48+this.AccountingInformation.size()+this.ProcurementCardIssuingInstitutes.size()+this.QualityManagement.size())
        {
            java.lang.Object QualityManagement = this.QualityManagement.get(propertyIndex-(48+this.AccountingInformation.size()+this.ProcurementCardIssuingInstitutes.size()));
            return QualityManagement!=null?QualityManagement:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex>=48+this.AccountingInformation.size()+this.ProcurementCardIssuingInstitutes.size()+this.QualityManagement.size() && propertyIndex < 48+this.AccountingInformation.size()+this.ProcurementCardIssuingInstitutes.size()+this.QualityManagement.size()+this.ProcurementArrangement.size())
        {
            java.lang.Object ProcurementArrangement = this.ProcurementArrangement.get(propertyIndex-(48+this.AccountingInformation.size()+this.ProcurementCardIssuingInstitutes.size()+this.QualityManagement.size()));
            return ProcurementArrangement!=null?ProcurementArrangement:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex>=48+this.AccountingInformation.size()+this.ProcurementCardIssuingInstitutes.size()+this.QualityManagement.size()+this.ProcurementArrangement.size() && propertyIndex < 48+this.AccountingInformation.size()+this.ProcurementCardIssuingInstitutes.size()+this.QualityManagement.size()+this.ProcurementArrangement.size()+this.SubRange.size())
        {
            java.lang.Object SubRange = this.SubRange.get(propertyIndex-(48+this.AccountingInformation.size()+this.ProcurementCardIssuingInstitutes.size()+this.QualityManagement.size()+this.ProcurementArrangement.size()));
            return SubRange!=null?SubRange:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex>=48+this.AccountingInformation.size()+this.ProcurementCardIssuingInstitutes.size()+this.QualityManagement.size()+this.ProcurementArrangement.size()+this.SubRange.size() && propertyIndex < 48+this.AccountingInformation.size()+this.ProcurementCardIssuingInstitutes.size()+this.QualityManagement.size()+this.ProcurementArrangement.size()+this.SubRange.size()+this.TaxGrouping.size())
        {
            java.lang.Object TaxGrouping = this.TaxGrouping.get(propertyIndex-(48+this.AccountingInformation.size()+this.ProcurementCardIssuingInstitutes.size()+this.QualityManagement.size()+this.ProcurementArrangement.size()+this.SubRange.size()));
            return TaxGrouping!=null?TaxGrouping:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex>=48+this.AccountingInformation.size()+this.ProcurementCardIssuingInstitutes.size()+this.QualityManagement.size()+this.ProcurementArrangement.size()+this.SubRange.size()+this.TaxGrouping.size() && propertyIndex < 48+this.AccountingInformation.size()+this.ProcurementCardIssuingInstitutes.size()+this.QualityManagement.size()+this.ProcurementArrangement.size()+this.SubRange.size()+this.TaxGrouping.size()+this.SupplierText.size())
        {
            java.lang.Object SupplierText = this.SupplierText.get(propertyIndex-(48+this.AccountingInformation.size()+this.ProcurementCardIssuingInstitutes.size()+this.QualityManagement.size()+this.ProcurementArrangement.size()+this.SubRange.size()+this.TaxGrouping.size()));
            return SupplierText!=null?SupplierText:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex>=48+this.AccountingInformation.size()+this.ProcurementCardIssuingInstitutes.size()+this.QualityManagement.size()+this.ProcurementArrangement.size()+this.SubRange.size()+this.TaxGrouping.size()+this.SupplierText.size() && propertyIndex < 48+this.AccountingInformation.size()+this.ProcurementCardIssuingInstitutes.size()+this.QualityManagement.size()+this.ProcurementArrangement.size()+this.SubRange.size()+this.TaxGrouping.size()+this.SupplierText.size()+this.SupplierDocument.size())
        {
            java.lang.Object SupplierDocument = this.SupplierDocument.get(propertyIndex-(48+this.AccountingInformation.size()+this.ProcurementCardIssuingInstitutes.size()+this.QualityManagement.size()+this.ProcurementArrangement.size()+this.SubRange.size()+this.TaxGrouping.size()+this.SupplierText.size()));
            return SupplierDocument!=null?SupplierDocument:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex>=48+this.AccountingInformation.size()+this.ProcurementCardIssuingInstitutes.size()+this.QualityManagement.size()+this.ProcurementArrangement.size()+this.SubRange.size()+this.TaxGrouping.size()+this.SupplierText.size()+this.SupplierDocument.size() && propertyIndex < 48+this.AccountingInformation.size()+this.ProcurementCardIssuingInstitutes.size()+this.QualityManagement.size()+this.ProcurementArrangement.size()+this.SubRange.size()+this.TaxGrouping.size()+this.SupplierText.size()+this.SupplierDocument.size()+this.GenericCustomField.size())
        {
            return  this.GenericCustomField.get(propertyIndex-(48+this.AccountingInformation.size()+this.ProcurementCardIssuingInstitutes.size()+this.QualityManagement.size()+this.ProcurementArrangement.size()+this.SubRange.size()+this.TaxGrouping.size()+this.SupplierText.size()+this.SupplierDocument.size())).getSimpleValue();
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 48+AccountingInformation.size()+ProcurementCardIssuingInstitutes.size()+QualityManagement.size()+ProcurementArrangement.size()+SubRange.size()+TaxGrouping.size()+SupplierText.size()+SupplierDocument.size()+GenericCustomField.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "InternalID";
            info.namespace= "";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ReceiverInternalID";
            info.namespace= "";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "CreditorInformationNumber";
            info.namespace= "";
        }
        if(propertyIndex==3)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "MaintenanceProfileCode";
            info.namespace= "";
        }
        if(propertyIndex==4)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "ProcurementTransactionBlockingCode";
            info.namespace= "";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "DeletionBlockedIndicator";
            info.namespace= "";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "DeletedIndicator";
            info.namespace= "";
        }
        if(propertyIndex==7)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "PostingBlockedIndicator";
            info.namespace= "";
        }
        if(propertyIndex==8)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "PurchasingBlockedIndicator";
            info.namespace= "";
        }
        if(propertyIndex==9)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "TradingPartnerCompanyID";
            info.namespace= "";
        }
        if(propertyIndex==10)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ManufacturerPartyID";
            info.namespace= "";
        }
        if(propertyIndex==11)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "AuthorisationGroupCode";
            info.namespace= "";
        }
        if(propertyIndex==12)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "CorporateGroupName";
            info.namespace= "";
        }
        if(propertyIndex==13)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ProofOfDeliveryRequirementCode";
            info.namespace= "";
        }
        if(propertyIndex==14)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "CreditDataLastCheckDate";
            info.namespace= "";
        }
        if(propertyIndex==15)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "TrainStationLocationName";
            info.namespace= "";
        }
        if(propertyIndex==16)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "DataMediumExchangeReportCode";
            info.namespace= "";
        }
        if(propertyIndex==17)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "DataMediumExchangeInstructionCode";
            info.namespace= "";
        }
        if(propertyIndex==18)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "InpaymentSlipWithReferenceNumberSubscriberID";
            info.namespace= "";
        }
        if(propertyIndex==19)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "AlternativePayeePartyInternalID";
            info.namespace= "";
        }
        if(propertyIndex==20)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "ReceiverAlternativePayeePartyInternalID";
            info.namespace= "";
        }
        if(propertyIndex==21)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "AlternativePayeeAllowedIndicator";
            info.namespace= "";
        }
        if(propertyIndex==22)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "EqualizationTaxRelevanceIndicator";
            info.namespace= "";
        }
        if(propertyIndex==23)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "ValueAddedTaxRelevanceIndicator";
            info.namespace= "";
        }
        if(propertyIndex==24)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "FiscalAddressPartyInternalID";
            info.namespace= "";
        }
        if(propertyIndex==25)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "ReceiverFiscalAddressPartyInternalID";
            info.namespace= "";
        }
        if(propertyIndex==26)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "SupplyingPlantID";
            info.namespace= "";
        }
        if(propertyIndex==27)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "SellerAssortmentProductGroupLevelRelevanceIndicator";
            info.namespace= "";
        }
        if(propertyIndex==28)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "PlantLevelRelevanceIndicator";
            info.namespace= "";
        }
        if(propertyIndex==29)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "WorkingDayCalendarCode";
            info.namespace= "";
        }
        if(propertyIndex==30)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "CarrierPartyStandardID";
            info.namespace= "";
        }
        if(propertyIndex==31)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "CarrierPartyFreightGroupCode";
            info.namespace= "";
        }
        if(propertyIndex==32)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "ServicePerformerPartyGroupCode";
            info.namespace= "";
        }
        if(propertyIndex==33)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "StatisticsGroupCode";
            info.namespace= "";
        }
        if(propertyIndex==34)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "TaxAuthorityPartyID";
            info.namespace= "";
        }
        if(propertyIndex==35)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "TaxGroupCode";
            info.namespace= "";
        }
        if(propertyIndex==36)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "SocialInsuranceActivityCode";
            info.namespace= "";
        }
        if(propertyIndex==37)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "ForSocialInsuranceRegisteredIndicator";
            info.namespace= "";
        }
        if(propertyIndex==38)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "TaxSplitIndicator";
            info.namespace= "";
        }
        if(propertyIndex==39)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "TaxBasePercentageCode";
            info.namespace= "";
        }
        if(propertyIndex==40)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "ResponsibleTaxOfficePartyInternalID";
            info.namespace= "";
        }
        if(propertyIndex==41)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "ReceiverResponsibleTaxOfficePartyInternalID";
            info.namespace= "";
        }
        if(propertyIndex==42)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "RepresentativeName";
            info.namespace= "";
        }
        if(propertyIndex==43)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "BusinessTypeName";
            info.namespace= "";
        }
        if(propertyIndex==44)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "IndustryTypeName";
            info.namespace= "";
        }
        if(propertyIndex==45)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "RelatedCustomerInternalID";
            info.namespace= "";
        }
        if(propertyIndex==46)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ReceiverRelatedCustomerInternalID";
            info.namespace= "";
        }
        if(propertyIndex>=47 && propertyIndex < 47+this.AccountingInformation.size())
        {
            info.type = QBSBPSUITERplctReqAcctgInfo.class;
            info.name = "AccountingInformation";
            info.namespace= "";
        }
        if(propertyIndex==47+this.AccountingInformation.size())
        {
            info.type = QBSBPSUITERplctReqBiddingCharc.class;
            info.name = "BiddingCharacteristic";
            info.namespace= "";
        }
        if(propertyIndex>=48+this.AccountingInformation.size() && propertyIndex < 48+this.AccountingInformation.size()+this.ProcurementCardIssuingInstitutes.size())
        {
            info.type = QBSBPSUITERplctReqProcmtCardIssuingInstitutes.class;
            info.name = "ProcurementCardIssuingInstitutes";
            info.namespace= "";
        }
        if(propertyIndex>=48+this.AccountingInformation.size()+this.ProcurementCardIssuingInstitutes.size() && propertyIndex < 48+this.AccountingInformation.size()+this.ProcurementCardIssuingInstitutes.size()+this.QualityManagement.size())
        {
            info.type = QBSBPSUITERplctReqQltyMgmt.class;
            info.name = "QualityManagement";
            info.namespace= "";
        }
        if(propertyIndex>=48+this.AccountingInformation.size()+this.ProcurementCardIssuingInstitutes.size()+this.QualityManagement.size() && propertyIndex < 48+this.AccountingInformation.size()+this.ProcurementCardIssuingInstitutes.size()+this.QualityManagement.size()+this.ProcurementArrangement.size())
        {
            info.type = QBSBPSUITERplctReqProcmtArrgmt.class;
            info.name = "ProcurementArrangement";
            info.namespace= "";
        }
        if(propertyIndex>=48+this.AccountingInformation.size()+this.ProcurementCardIssuingInstitutes.size()+this.QualityManagement.size()+this.ProcurementArrangement.size() && propertyIndex < 48+this.AccountingInformation.size()+this.ProcurementCardIssuingInstitutes.size()+this.QualityManagement.size()+this.ProcurementArrangement.size()+this.SubRange.size())
        {
            info.type = QBSBPSUITERplctReqSubRnge.class;
            info.name = "SubRange";
            info.namespace= "";
        }
        if(propertyIndex>=48+this.AccountingInformation.size()+this.ProcurementCardIssuingInstitutes.size()+this.QualityManagement.size()+this.ProcurementArrangement.size()+this.SubRange.size() && propertyIndex < 48+this.AccountingInformation.size()+this.ProcurementCardIssuingInstitutes.size()+this.QualityManagement.size()+this.ProcurementArrangement.size()+this.SubRange.size()+this.TaxGrouping.size())
        {
            info.type = QBSBPSUITERplctReqTxGrpg.class;
            info.name = "TaxGrouping";
            info.namespace= "";
        }
        if(propertyIndex>=48+this.AccountingInformation.size()+this.ProcurementCardIssuingInstitutes.size()+this.QualityManagement.size()+this.ProcurementArrangement.size()+this.SubRange.size()+this.TaxGrouping.size() && propertyIndex < 48+this.AccountingInformation.size()+this.ProcurementCardIssuingInstitutes.size()+this.QualityManagement.size()+this.ProcurementArrangement.size()+this.SubRange.size()+this.TaxGrouping.size()+this.SupplierText.size())
        {
            info.type = QBSBPSUITERplctReqText.class;
            info.name = "SupplierText";
            info.namespace= "";
        }
        if(propertyIndex>=48+this.AccountingInformation.size()+this.ProcurementCardIssuingInstitutes.size()+this.QualityManagement.size()+this.ProcurementArrangement.size()+this.SubRange.size()+this.TaxGrouping.size()+this.SupplierText.size() && propertyIndex < 48+this.AccountingInformation.size()+this.ProcurementCardIssuingInstitutes.size()+this.QualityManagement.size()+this.ProcurementArrangement.size()+this.SubRange.size()+this.TaxGrouping.size()+this.SupplierText.size()+this.SupplierDocument.size())
        {
            info.type = QBSBPSUITERplctReqDoc.class;
            info.name = "SupplierDocument";
            info.namespace= "";
        }
        if(propertyIndex>=48+this.AccountingInformation.size()+this.ProcurementCardIssuingInstitutes.size()+this.QualityManagement.size()+this.ProcurementArrangement.size()+this.SubRange.size()+this.TaxGrouping.size()+this.SupplierText.size()+this.SupplierDocument.size() && propertyIndex < 48+this.AccountingInformation.size()+this.ProcurementCardIssuingInstitutes.size()+this.QualityManagement.size()+this.ProcurementArrangement.size()+this.SubRange.size()+this.TaxGrouping.size()+this.SupplierText.size()+this.SupplierDocument.size()+this.GenericCustomField.size())
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "GenericCustomField";
            info.namespace= "http://ariba.com/xi/SupplierManagement";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }



    @Override
    public int getAttributeCount() {
        return 8;
    }
    
    @Override
    public void getAttributeInfo(int index, AttributeInfo info) {
        if(index==0)
        {
            info.name = "accountingInformationListCompleteTransmissionIndicator";
            info.namespace= "";
            if(this.accountingInformationListCompleteTransmissionIndicator!=null)
            {
                info.setValue(this.accountingInformationListCompleteTransmissionIndicator);
            }
            
        }
        if(index==1)
        {
            info.name = "biddingCharacteristicListCompleteTransmissionIndicator";
            info.namespace= "";
            if(this.biddingCharacteristicListCompleteTransmissionIndicator!=null)
            {
                info.setValue(this.biddingCharacteristicListCompleteTransmissionIndicator);
            }
            
        }
        if(index==2)
        {
            info.name = "procurementCardIssuingInstitutesListCompleteTransmissionIndicator";
            info.namespace= "";
            if(this.procurementCardIssuingInstitutesListCompleteTransmissionIndicator!=null)
            {
                info.setValue(this.procurementCardIssuingInstitutesListCompleteTransmissionIndicator);
            }
            
        }
        if(index==3)
        {
            info.name = "qualitiyManagementListCompleteTransmissionIndicator";
            info.namespace= "";
            if(this.qualitiyManagementListCompleteTransmissionIndicator!=null)
            {
                info.setValue(this.qualitiyManagementListCompleteTransmissionIndicator);
            }
            
        }
        if(index==4)
        {
            info.name = "procurementArrangementListCompleteTransmissionIndicator";
            info.namespace= "";
            if(this.procurementArrangementListCompleteTransmissionIndicator!=null)
            {
                info.setValue(this.procurementArrangementListCompleteTransmissionIndicator);
            }
            
        }
        if(index==5)
        {
            info.name = "subRangeListCompleteTransmissionIndicator";
            info.namespace= "";
            if(this.subRangeListCompleteTransmissionIndicator!=null)
            {
                info.setValue(this.subRangeListCompleteTransmissionIndicator);
            }
            
        }
        if(index==6)
        {
            info.name = "taxGroupingListCompleteTransmissionIndicator";
            info.namespace= "";
            if(this.taxGroupingListCompleteTransmissionIndicator!=null)
            {
                info.setValue(this.taxGroupingListCompleteTransmissionIndicator);
            }
            
        }
        if(index==7)
        {
            info.name = "supplierTextListCompleteTransmissionIndicator";
            info.namespace= "";
            if(this.supplierTextListCompleteTransmissionIndicator!=null)
            {
                info.setValue(this.supplierTextListCompleteTransmissionIndicator);
            }
            
        }
    }

    @Override
    public void getAttribute(int i, AttributeInfo attributeInfo) {

    }

    @Override
    public void setAttribute(AttributeInfo attributeInfo) {

    }    
}

