package com.exampleariba.aribasoup.gerado;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.2.0
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class QBSBPSUITERplctReqSalesAndDistrBlocks extends AttributeContainer implements KvmSerializable
{

    
    public String OrderBlockingReasonCode;
    
    public String BillingBlockingReasonCode;
    
    public String DeliveryBlockingReasonCode;
    
    public Boolean SalesSupportBlockedIndicator;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,QBSExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,QBSExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("OrderBlockingReasonCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.OrderBlockingReasonCode = j.toString();
                    }
                }
                else{
                    this.OrderBlockingReasonCode = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("BillingBlockingReasonCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.BillingBlockingReasonCode = j.toString();
                    }
                }
                else{
                    this.BillingBlockingReasonCode = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("DeliveryBlockingReasonCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.DeliveryBlockingReasonCode = j.toString();
                    }
                }
                else{
                    this.DeliveryBlockingReasonCode = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("SalesSupportBlockedIndicator"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.SalesSupportBlockedIndicator = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.SalesSupportBlockedIndicator = (Boolean)obj;
                }
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.OrderBlockingReasonCode!=null?this.OrderBlockingReasonCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.BillingBlockingReasonCode!=null?this.BillingBlockingReasonCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.DeliveryBlockingReasonCode!=null?this.DeliveryBlockingReasonCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.SalesSupportBlockedIndicator!=null?this.SalesSupportBlockedIndicator:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 4;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "OrderBlockingReasonCode";
            info.namespace= "";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "BillingBlockingReasonCode";
            info.namespace= "";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "DeliveryBlockingReasonCode";
            info.namespace= "";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "SalesSupportBlockedIndicator";
            info.namespace= "";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

