package com.exampleariba.aribasoup.gerado;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.2.0
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.util.ArrayList;
import org.ksoap2.serialization.PropertyInfo;

public class QBSBPRelshpSUITERplctReqCntctPersnWplcAddrInfoAddrWeb extends AttributeContainer implements KvmSerializable
{

    
    public String URI;
    
    public QBSCode URITypeCode;
    
    public Boolean UsageDeniedIndicator;
    
    public ArrayList< QBSBPRelshpSUITERplctReqCntctPersnWplcAddrInfoAddrWebUsge> WebUsage =new ArrayList<QBSBPRelshpSUITERplctReqCntctPersnWplcAddrInfoAddrWebUsge >();
    
    public String actionCode;
    
    public Boolean webUsageListCompleteTransmissionIndicator=false;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,QBSExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }
        if (inObj.hasAttribute("actionCode"))
        {	
            java.lang.Object j = inObj.getAttribute("actionCode");
            if (j != null)
            {
                actionCode = j.toString();
            }
        }
        if (inObj.hasAttribute("webUsageListCompleteTransmissionIndicator"))
        {	
            java.lang.Object j = inObj.getAttribute("webUsageListCompleteTransmissionIndicator");
            if (j != null)
            {
                webUsageListCompleteTransmissionIndicator = new Boolean(j.toString());
            }
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,QBSExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("URI"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.URI = j.toString();
                    }
                }
                else{
                    this.URI = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("URITypeCode"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.URITypeCode = (QBSCode)__envelope.get(j,QBSCode.class,false);
            }
            return true;
        }
        if (info.name.equals("UsageDeniedIndicator"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.UsageDeniedIndicator = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.UsageDeniedIndicator = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("WebUsage"))
        {
            if(obj!=null)
            {
                if(this.WebUsage==null)
                {
                    this.WebUsage = new java.util.ArrayList< QBSBPRelshpSUITERplctReqCntctPersnWplcAddrInfoAddrWebUsge>();
                }
                java.lang.Object j =obj;
                QBSBPRelshpSUITERplctReqCntctPersnWplcAddrInfoAddrWebUsge j1= (QBSBPRelshpSUITERplctReqCntctPersnWplcAddrInfoAddrWebUsge)__envelope.get(j,QBSBPRelshpSUITERplctReqCntctPersnWplcAddrInfoAddrWebUsge.class,false);
                this.WebUsage.add(j1);
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return URI;
        }
        if(propertyIndex==1)
        {
            return this.URITypeCode!=null?this.URITypeCode.getSimpleValue():null;
        }
        if(propertyIndex==2)
        {
            return this.UsageDeniedIndicator!=null?this.UsageDeniedIndicator:SoapPrimitive.NullSkip;
        }
        if(propertyIndex>=3 && propertyIndex < 3+this.WebUsage.size())
        {
            java.lang.Object WebUsage = this.WebUsage.get(propertyIndex-(3));
            return WebUsage!=null?WebUsage:SoapPrimitive.NullNilElement;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 3+WebUsage.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "URI";
            info.namespace= "";
        }
        if(propertyIndex==1)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "URITypeCode";
            info.namespace= "";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "UsageDeniedIndicator";
            info.namespace= "";
        }
        if(propertyIndex>=3 && propertyIndex < 3+this.WebUsage.size())
        {
            info.type = QBSBPRelshpSUITERplctReqCntctPersnWplcAddrInfoAddrWebUsge.class;
            info.name = "WebUsage";
            info.namespace= "";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }



    @Override
    public int getAttributeCount() {
        return 2;
    }
    
    @Override
    public void getAttributeInfo(int index, AttributeInfo info) {
        if(index==0)
        {
            info.name = "actionCode";
            info.namespace= "";
            if(this.actionCode!=null)
            {
                info.setValue(this.actionCode);
            }
            
        }
        if(index==1)
        {
            info.name = "webUsageListCompleteTransmissionIndicator";
            info.namespace= "";
            if(this.webUsageListCompleteTransmissionIndicator!=null)
            {
                info.setValue(this.webUsageListCompleteTransmissionIndicator);
            }
            
        }
    }

    @Override
    public void getAttribute(int i, AttributeInfo attributeInfo) {

    }

    @Override
    public void setAttribute(AttributeInfo attributeInfo) {

    }    
}

