package com.exampleariba.aribasoup.gerado;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.2.0
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.util.ArrayList;
import org.ksoap2.serialization.PropertyInfo;

public class QBSBPRelshpSUITERplctReqCntctPersn extends AttributeContainer implements KvmSerializable
{

    
    public QBSBusinessPartnerFunctionTypeCode BusinessPartnerFunctionTypeCode;
    
    public QBSBusinessPartnerFunctionalAreaCode BusinessPartnerFunctionalAreaCode;
    
    public QBSPowerOfAttorneyTypeCode PowerOfAttorneyTypeCode;
    
    public QBSVIPReasonCode VIPReasonCode;
    
    public String ContactPersonNote;
    
    public ArrayList< QBSBPRelshpSUITERplctReqCntctPersnWplcAddrInfo> WorkplaceAddressInformation =new ArrayList<QBSBPRelshpSUITERplctReqCntctPersnWplcAddrInfo >();
    
    public QBSBPRelshpSUITERplctReqCustSuplrCntctPersn CustomerContactPerson;
    
    public QBSBPRelshpSUITERplctReqCustSuplrCntctPersn SupplierContactPerson;
    
    public String actionCode;
    
    public Boolean workplaceAddressListCompleteTransmissionIndicator=false;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,QBSExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }
        if (inObj.hasAttribute("actionCode"))
        {	
            java.lang.Object j = inObj.getAttribute("actionCode");
            if (j != null)
            {
                actionCode = j.toString();
            }
        }
        if (inObj.hasAttribute("workplaceAddressListCompleteTransmissionIndicator"))
        {	
            java.lang.Object j = inObj.getAttribute("workplaceAddressListCompleteTransmissionIndicator");
            if (j != null)
            {
                workplaceAddressListCompleteTransmissionIndicator = new Boolean(j.toString());
            }
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,QBSExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("BusinessPartnerFunctionTypeCode"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.BusinessPartnerFunctionTypeCode = (QBSBusinessPartnerFunctionTypeCode)__envelope.get(j,QBSBusinessPartnerFunctionTypeCode.class,false);
            }
            return true;
        }
        if (info.name.equals("BusinessPartnerFunctionalAreaCode"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.BusinessPartnerFunctionalAreaCode = (QBSBusinessPartnerFunctionalAreaCode)__envelope.get(j,QBSBusinessPartnerFunctionalAreaCode.class,false);
            }
            return true;
        }
        if (info.name.equals("PowerOfAttorneyTypeCode"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.PowerOfAttorneyTypeCode = (QBSPowerOfAttorneyTypeCode)__envelope.get(j,QBSPowerOfAttorneyTypeCode.class,false);
            }
            return true;
        }
        if (info.name.equals("VIPReasonCode"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.VIPReasonCode = (QBSVIPReasonCode)__envelope.get(j,QBSVIPReasonCode.class,false);
            }
            return true;
        }
        if (info.name.equals("ContactPersonNote"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ContactPersonNote = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.ContactPersonNote = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("WorkplaceAddressInformation"))
        {
            if(obj!=null)
            {
                if(this.WorkplaceAddressInformation==null)
                {
                    this.WorkplaceAddressInformation = new java.util.ArrayList< QBSBPRelshpSUITERplctReqCntctPersnWplcAddrInfo>();
                }
                java.lang.Object j =obj;
                QBSBPRelshpSUITERplctReqCntctPersnWplcAddrInfo j1= (QBSBPRelshpSUITERplctReqCntctPersnWplcAddrInfo)__envelope.get(j,QBSBPRelshpSUITERplctReqCntctPersnWplcAddrInfo.class,false);
                this.WorkplaceAddressInformation.add(j1);
            }
            return true;
        }
        if (info.name.equals("CustomerContactPerson"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.CustomerContactPerson = (QBSBPRelshpSUITERplctReqCustSuplrCntctPersn)__envelope.get(j,QBSBPRelshpSUITERplctReqCustSuplrCntctPersn.class,false);
            }
            return true;
        }
        if (info.name.equals("SupplierContactPerson"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.SupplierContactPerson = (QBSBPRelshpSUITERplctReqCustSuplrCntctPersn)__envelope.get(j,QBSBPRelshpSUITERplctReqCustSuplrCntctPersn.class,false);
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.BusinessPartnerFunctionTypeCode!=null?this.BusinessPartnerFunctionTypeCode.getSimpleValue():null;
        }
        if(propertyIndex==1)
        {
            return this.BusinessPartnerFunctionalAreaCode!=null?this.BusinessPartnerFunctionalAreaCode.getSimpleValue():null;
        }
        if(propertyIndex==2)
        {
            return this.PowerOfAttorneyTypeCode!=null?this.PowerOfAttorneyTypeCode.getSimpleValue():null;
        }
        if(propertyIndex==3)
        {
            return this.VIPReasonCode!=null?this.VIPReasonCode.getSimpleValue():null;
        }
        if(propertyIndex==4)
        {
            return this.ContactPersonNote!=null?this.ContactPersonNote:SoapPrimitive.NullSkip;
        }
        if(propertyIndex>=5 && propertyIndex < 5+this.WorkplaceAddressInformation.size())
        {
            java.lang.Object WorkplaceAddressInformation = this.WorkplaceAddressInformation.get(propertyIndex-(5));
            return WorkplaceAddressInformation!=null?WorkplaceAddressInformation:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==5+this.WorkplaceAddressInformation.size())
        {
            return this.CustomerContactPerson!=null?this.CustomerContactPerson:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6+this.WorkplaceAddressInformation.size())
        {
            return this.SupplierContactPerson!=null?this.SupplierContactPerson:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 7+WorkplaceAddressInformation.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "BusinessPartnerFunctionTypeCode";
            info.namespace= "";
        }
        if(propertyIndex==1)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "BusinessPartnerFunctionalAreaCode";
            info.namespace= "";
        }
        if(propertyIndex==2)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "PowerOfAttorneyTypeCode";
            info.namespace= "";
        }
        if(propertyIndex==3)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "VIPReasonCode";
            info.namespace= "";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ContactPersonNote";
            info.namespace= "";
        }
        if(propertyIndex>=5 && propertyIndex < 5+this.WorkplaceAddressInformation.size())
        {
            info.type = QBSBPRelshpSUITERplctReqCntctPersnWplcAddrInfo.class;
            info.name = "WorkplaceAddressInformation";
            info.namespace= "";
        }
        if(propertyIndex==5+this.WorkplaceAddressInformation.size())
        {
            info.type = QBSBPRelshpSUITERplctReqCustSuplrCntctPersn.class;
            info.name = "CustomerContactPerson";
            info.namespace= "";
        }
        if(propertyIndex==6+this.WorkplaceAddressInformation.size())
        {
            info.type = QBSBPRelshpSUITERplctReqCustSuplrCntctPersn.class;
            info.name = "SupplierContactPerson";
            info.namespace= "";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }



    @Override
    public int getAttributeCount() {
        return 2;
    }
    
    @Override
    public void getAttributeInfo(int index, AttributeInfo info) {
        if(index==0)
        {
            info.name = "actionCode";
            info.namespace= "";
            if(this.actionCode!=null)
            {
                info.setValue(this.actionCode);
            }
            
        }
        if(index==1)
        {
            info.name = "workplaceAddressListCompleteTransmissionIndicator";
            info.namespace= "";
            if(this.workplaceAddressListCompleteTransmissionIndicator!=null)
            {
                info.setValue(this.workplaceAddressListCompleteTransmissionIndicator);
            }
            
        }
    }

    @Override
    public void getAttribute(int i, AttributeInfo attributeInfo) {

    }

    @Override
    public void setAttribute(AttributeInfo attributeInfo) {

    }    
}

