package com.exampleariba.aribasoup.gerado;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.2.0
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class QBSBPSUITERplctReqDelivTrms extends AttributeContainer implements KvmSerializable
{

    
    public QBSCode DeliveryPriorityCode;
    
    public QBSIncoterms Incoterms;
    
    public Boolean SalesOrderCompleteDeliveryIndicator;
    
    public Boolean OrderCombinationAllowedIndicator;
    
    public String PartialDeliveryControlCode;
    
    public Integer PartialDeliveryMaximumNumberValue;
    
    public QBSQuantityTolerance QuantityTolerance;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,QBSExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,QBSExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("DeliveryPriorityCode"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.DeliveryPriorityCode = (QBSCode)__envelope.get(j,QBSCode.class,false);
            }
            return true;
        }
        if (info.name.equals("Incoterms"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Incoterms = (QBSIncoterms)__envelope.get(j,QBSIncoterms.class,false);
            }
            return true;
        }
        if (info.name.equals("SalesOrderCompleteDeliveryIndicator"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.SalesOrderCompleteDeliveryIndicator = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.SalesOrderCompleteDeliveryIndicator = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("OrderCombinationAllowedIndicator"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.OrderCombinationAllowedIndicator = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.OrderCombinationAllowedIndicator = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("PartialDeliveryControlCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.PartialDeliveryControlCode = j.toString();
                    }
                }
                else{
                    this.PartialDeliveryControlCode = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("PartialDeliveryMaximumNumberValue"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.PartialDeliveryMaximumNumberValue = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.PartialDeliveryMaximumNumberValue = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("QuantityTolerance"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.QuantityTolerance = (QBSQuantityTolerance)__envelope.get(j,QBSQuantityTolerance.class,false);
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.DeliveryPriorityCode!=null?this.DeliveryPriorityCode.getSimpleValue():null;
        }
        if(propertyIndex==1)
        {
            return this.Incoterms!=null?this.Incoterms:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.SalesOrderCompleteDeliveryIndicator!=null?this.SalesOrderCompleteDeliveryIndicator:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.OrderCombinationAllowedIndicator!=null?this.OrderCombinationAllowedIndicator:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.PartialDeliveryControlCode!=null?this.PartialDeliveryControlCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.PartialDeliveryMaximumNumberValue!=null?this.PartialDeliveryMaximumNumberValue:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.QuantityTolerance!=null?this.QuantityTolerance:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 7;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "DeliveryPriorityCode";
            info.namespace= "";
        }
        if(propertyIndex==1)
        {
            info.type = QBSIncoterms.class;
            info.name = "Incoterms";
            info.namespace= "";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "SalesOrderCompleteDeliveryIndicator";
            info.namespace= "";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "OrderCombinationAllowedIndicator";
            info.namespace= "";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "PartialDeliveryControlCode";
            info.namespace= "";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "PartialDeliveryMaximumNumberValue";
            info.namespace= "";
        }
        if(propertyIndex==6)
        {
            info.type = QBSQuantityTolerance.class;
            info.name = "QuantityTolerance";
            info.namespace= "";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

