package com.exampleariba.aribasoup.gerado;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.2.0
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class QBSBPRelshpSUITERplctReqCntctPersnWplcAddrInfoAddrWplc extends AttributeContainer implements KvmSerializable
{

    
    public QBSAddressRepresentationCode AddressRepresentationCode;
    
    public String FunctionalTitleName;
    
    public String DepartmentName;
    
    public String BuildingID;
    
    public String FloorID;
    
    public String RoomID;
    
    public String InhouseMailID;
    
    public String CorrespondenceShortName;
    
    public String actionCode;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,QBSExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }
        if (inObj.hasAttribute("actionCode"))
        {	
            java.lang.Object j = inObj.getAttribute("actionCode");
            if (j != null)
            {
                actionCode = j.toString();
            }
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,QBSExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("AddressRepresentationCode"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.AddressRepresentationCode = (QBSAddressRepresentationCode)__envelope.get(j,QBSAddressRepresentationCode.class,false);
            }
            return true;
        }
        if (info.name.equals("FunctionalTitleName"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.FunctionalTitleName = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.FunctionalTitleName = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("DepartmentName"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.DepartmentName = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.DepartmentName = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("BuildingID"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.BuildingID = j.toString();
                    }
                }
                else{
                    this.BuildingID = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("FloorID"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.FloorID = j.toString();
                    }
                }
                else{
                    this.FloorID = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("RoomID"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.RoomID = j.toString();
                    }
                }
                else{
                    this.RoomID = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("InhouseMailID"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.InhouseMailID = j.toString();
                    }
                }
                else{
                    this.InhouseMailID = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("CorrespondenceShortName"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.CorrespondenceShortName = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.CorrespondenceShortName = (String)obj;
                }
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.AddressRepresentationCode!=null?this.AddressRepresentationCode.getSimpleValue():null;
        }
        if(propertyIndex==1)
        {
            return this.FunctionalTitleName!=null?this.FunctionalTitleName:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.DepartmentName!=null?this.DepartmentName:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.BuildingID!=null?this.BuildingID:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.FloorID!=null?this.FloorID:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.RoomID!=null?this.RoomID:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.InhouseMailID!=null?this.InhouseMailID:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==7)
        {
            return this.CorrespondenceShortName!=null?this.CorrespondenceShortName:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 8;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "AddressRepresentationCode";
            info.namespace= "";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "FunctionalTitleName";
            info.namespace= "";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "DepartmentName";
            info.namespace= "";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "BuildingID";
            info.namespace= "";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "FloorID";
            info.namespace= "";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "RoomID";
            info.namespace= "";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "InhouseMailID";
            info.namespace= "";
        }
        if(propertyIndex==7)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "CorrespondenceShortName";
            info.namespace= "";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }



    @Override
    public int getAttributeCount() {
        return 1;
    }
    
    @Override
    public void getAttributeInfo(int index, AttributeInfo info) {
        if(index==0)
        {
            info.name = "actionCode";
            info.namespace= "";
            if(this.actionCode!=null)
            {
                info.setValue(this.actionCode);
            }
            
        }
    }

    @Override
    public void getAttribute(int i, AttributeInfo attributeInfo) {

    }

    @Override
    public void setAttribute(AttributeInfo attributeInfo) {

    }    
}

