package com.exampleariba.aribasoup.gerado;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.2.0
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class QBSBPSUITERplctReqCustWhldgTx extends AttributeContainer implements KvmSerializable
{

    
    public QBSCode WithholdingTaxTypeCode;
    
    public QBSCode WithholdingTaxIdentificationNumber;
    
    public QBSCode WithholdingTaxCode;
    
    public Boolean WithholdingTaxAgentIndicator;
    
    public QBSCLOSED_DatePeriod WithholdingTaxObligationPeriod;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,QBSExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,QBSExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("WithholdingTaxTypeCode"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.WithholdingTaxTypeCode = (QBSCode)__envelope.get(j,QBSCode.class,false);
            }
            return true;
        }
        if (info.name.equals("WithholdingTaxIdentificationNumber"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.WithholdingTaxIdentificationNumber = (QBSCode)__envelope.get(j,QBSCode.class,false);
            }
            return true;
        }
        if (info.name.equals("WithholdingTaxCode"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.WithholdingTaxCode = (QBSCode)__envelope.get(j,QBSCode.class,false);
            }
            return true;
        }
        if (info.name.equals("WithholdingTaxAgentIndicator"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.WithholdingTaxAgentIndicator = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.WithholdingTaxAgentIndicator = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("WithholdingTaxObligationPeriod"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.WithholdingTaxObligationPeriod = (QBSCLOSED_DatePeriod)__envelope.get(j,QBSCLOSED_DatePeriod.class,false);
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.WithholdingTaxTypeCode!=null?this.WithholdingTaxTypeCode.getSimpleValue():null;
        }
        if(propertyIndex==1)
        {
            return this.WithholdingTaxIdentificationNumber!=null?this.WithholdingTaxIdentificationNumber.getSimpleValue():null;
        }
        if(propertyIndex==2)
        {
            return this.WithholdingTaxCode!=null?this.WithholdingTaxCode.getSimpleValue():null;
        }
        if(propertyIndex==3)
        {
            return this.WithholdingTaxAgentIndicator!=null?this.WithholdingTaxAgentIndicator:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.WithholdingTaxObligationPeriod!=null?this.WithholdingTaxObligationPeriod:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 5;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "WithholdingTaxTypeCode";
            info.namespace= "";
        }
        if(propertyIndex==1)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "WithholdingTaxIdentificationNumber";
            info.namespace= "";
        }
        if(propertyIndex==2)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "WithholdingTaxCode";
            info.namespace= "";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "WithholdingTaxAgentIndicator";
            info.namespace= "";
        }
        if(propertyIndex==4)
        {
            info.type = QBSCLOSED_DatePeriod.class;
            info.name = "WithholdingTaxObligationPeriod";
            info.namespace= "";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

