package com.exampleariba.aribasoup.gerado;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.2.0
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class QBSBPSUITERplctConfBP extends AttributeContainer implements KvmSerializable
{

    
    public QBSUUID UUID;
    
    public String InternalID;
    
    public QBSUUID ReceiverUUID;
    
    public String ReceiverInternalID;
    
    public QBSBPSUITERplctConfCust Customer;
    
    public QBSBPSUITERplctConfSuplr Supplier;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,QBSExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,QBSExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("UUID"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.UUID = (QBSUUID)__envelope.get(j,QBSUUID.class,false);
            }
            return true;
        }
        if (info.name.equals("InternalID"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.InternalID = j.toString();
                    }
                }
                else{
                    this.InternalID = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("ReceiverUUID"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.ReceiverUUID = (QBSUUID)__envelope.get(j,QBSUUID.class,false);
            }
            return true;
        }
        if (info.name.equals("ReceiverInternalID"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ReceiverInternalID = j.toString();
                    }
                }
                else{
                    this.ReceiverInternalID = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("Customer"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Customer = (QBSBPSUITERplctConfCust)__envelope.get(j,QBSBPSUITERplctConfCust.class,false);
            }
            return true;
        }
        if (info.name.equals("Supplier"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Supplier = (QBSBPSUITERplctConfSuplr)__envelope.get(j,QBSBPSUITERplctConfSuplr.class,false);
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.UUID!=null?this.UUID.getSimpleValue():null;
        }
        if(propertyIndex==1)
        {
            return this.InternalID!=null?this.InternalID:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.ReceiverUUID!=null?this.ReceiverUUID.getSimpleValue():null;
        }
        if(propertyIndex==3)
        {
            return this.ReceiverInternalID!=null?this.ReceiverInternalID:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.Customer!=null?this.Customer:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.Supplier!=null?this.Supplier:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 6;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "UUID";
            info.namespace= "";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "InternalID";
            info.namespace= "";
        }
        if(propertyIndex==2)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "ReceiverUUID";
            info.namespace= "";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ReceiverInternalID";
            info.namespace= "";
        }
        if(propertyIndex==4)
        {
            info.type = QBSBPSUITERplctConfCust.class;
            info.name = "Customer";
            info.namespace= "";
        }
        if(propertyIndex==5)
        {
            info.type = QBSBPSUITERplctConfSuplr.class;
            info.name = "Supplier";
            info.namespace= "";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

