package com.exampleariba.aribasoup.gerado;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.2.0
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class QBSBPSUITERplctReqPrSpecs extends AttributeContainer implements KvmSerializable
{

    
    public QBSPriceSpecificationCustomerGroupCode CustomerConditionGroupCode;
    
    public QBSPriceSpecificationCustomerGroupCode FirstAdditionalCustomerConditionGroupCode;
    
    public QBSPriceSpecificationCustomerGroupCode SecondAdditionalCustomerConditionGroupCode;
    
    public QBSPriceSpecificationCustomerGroupCode ThirdAdditionalCustomerConditionGroupCode;
    
    public QBSPriceSpecificationCustomerGroupCode FourthAdditionalCustomerConditionGroupCode;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,QBSExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,QBSExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("CustomerConditionGroupCode"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.CustomerConditionGroupCode = (QBSPriceSpecificationCustomerGroupCode)__envelope.get(j,QBSPriceSpecificationCustomerGroupCode.class,false);
            }
            return true;
        }
        if (info.name.equals("FirstAdditionalCustomerConditionGroupCode"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.FirstAdditionalCustomerConditionGroupCode = (QBSPriceSpecificationCustomerGroupCode)__envelope.get(j,QBSPriceSpecificationCustomerGroupCode.class,false);
            }
            return true;
        }
        if (info.name.equals("SecondAdditionalCustomerConditionGroupCode"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.SecondAdditionalCustomerConditionGroupCode = (QBSPriceSpecificationCustomerGroupCode)__envelope.get(j,QBSPriceSpecificationCustomerGroupCode.class,false);
            }
            return true;
        }
        if (info.name.equals("ThirdAdditionalCustomerConditionGroupCode"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.ThirdAdditionalCustomerConditionGroupCode = (QBSPriceSpecificationCustomerGroupCode)__envelope.get(j,QBSPriceSpecificationCustomerGroupCode.class,false);
            }
            return true;
        }
        if (info.name.equals("FourthAdditionalCustomerConditionGroupCode"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.FourthAdditionalCustomerConditionGroupCode = (QBSPriceSpecificationCustomerGroupCode)__envelope.get(j,QBSPriceSpecificationCustomerGroupCode.class,false);
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.CustomerConditionGroupCode!=null?this.CustomerConditionGroupCode.getSimpleValue():null;
        }
        if(propertyIndex==1)
        {
            return this.FirstAdditionalCustomerConditionGroupCode!=null?this.FirstAdditionalCustomerConditionGroupCode.getSimpleValue():null;
        }
        if(propertyIndex==2)
        {
            return this.SecondAdditionalCustomerConditionGroupCode!=null?this.SecondAdditionalCustomerConditionGroupCode.getSimpleValue():null;
        }
        if(propertyIndex==3)
        {
            return this.ThirdAdditionalCustomerConditionGroupCode!=null?this.ThirdAdditionalCustomerConditionGroupCode.getSimpleValue():null;
        }
        if(propertyIndex==4)
        {
            return this.FourthAdditionalCustomerConditionGroupCode!=null?this.FourthAdditionalCustomerConditionGroupCode.getSimpleValue():null;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 5;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "CustomerConditionGroupCode";
            info.namespace= "";
        }
        if(propertyIndex==1)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "FirstAdditionalCustomerConditionGroupCode";
            info.namespace= "";
        }
        if(propertyIndex==2)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "SecondAdditionalCustomerConditionGroupCode";
            info.namespace= "";
        }
        if(propertyIndex==3)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "ThirdAdditionalCustomerConditionGroupCode";
            info.namespace= "";
        }
        if(propertyIndex==4)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "FourthAdditionalCustomerConditionGroupCode";
            info.namespace= "";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

