package com.exampleariba.aribasoup.gerado;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.2.0
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class QBSBPRelshpSUITERplctConfBPRelshp extends AttributeContainer implements KvmSerializable
{

    
    public QBSUUID BusinessPartnerUUID;
    
    public String BusinessPartnerInternalID;
    
    public QBSUUID ReceiverBusinessPartnerUUID;
    
    public String ReceiverBusinessPartnerInternalID;
    
    public QBSUUID RelatedBusinessPartnerUUID;
    
    public String RelatedBusinessPartnerInternalID;
    
    public QBSUUID ReceiverRelatedBusinessPartnerUUID;
    
    public String ReceiverRelatedBusinessPartnerInternalID;
    
    public QBSMDGBusinessPartnerRelationshipCategoryCode RoleCode;
    
    public QBSCLOSED_DatePeriod ValidityPeriod;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,QBSExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,QBSExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("BusinessPartnerUUID"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.BusinessPartnerUUID = (QBSUUID)__envelope.get(j,QBSUUID.class,false);
            }
            return true;
        }
        if (info.name.equals("BusinessPartnerInternalID"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.BusinessPartnerInternalID = j.toString();
                    }
                }
                else{
                    this.BusinessPartnerInternalID = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("ReceiverBusinessPartnerUUID"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.ReceiverBusinessPartnerUUID = (QBSUUID)__envelope.get(j,QBSUUID.class,false);
            }
            return true;
        }
        if (info.name.equals("ReceiverBusinessPartnerInternalID"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ReceiverBusinessPartnerInternalID = j.toString();
                    }
                }
                else{
                    this.ReceiverBusinessPartnerInternalID = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("RelatedBusinessPartnerUUID"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.RelatedBusinessPartnerUUID = (QBSUUID)__envelope.get(j,QBSUUID.class,false);
            }
            return true;
        }
        if (info.name.equals("RelatedBusinessPartnerInternalID"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.RelatedBusinessPartnerInternalID = j.toString();
                    }
                }
                else{
                    this.RelatedBusinessPartnerInternalID = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("ReceiverRelatedBusinessPartnerUUID"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.ReceiverRelatedBusinessPartnerUUID = (QBSUUID)__envelope.get(j,QBSUUID.class,false);
            }
            return true;
        }
        if (info.name.equals("ReceiverRelatedBusinessPartnerInternalID"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ReceiverRelatedBusinessPartnerInternalID = j.toString();
                    }
                }
                else{
                    this.ReceiverRelatedBusinessPartnerInternalID = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("RoleCode"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.RoleCode = (QBSMDGBusinessPartnerRelationshipCategoryCode)__envelope.get(j,QBSMDGBusinessPartnerRelationshipCategoryCode.class,false);
            }
            return true;
        }
        if (info.name.equals("ValidityPeriod"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.ValidityPeriod = (QBSCLOSED_DatePeriod)__envelope.get(j,QBSCLOSED_DatePeriod.class,false);
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.BusinessPartnerUUID!=null?this.BusinessPartnerUUID.getSimpleValue():null;
        }
        if(propertyIndex==1)
        {
            return this.BusinessPartnerInternalID!=null?this.BusinessPartnerInternalID:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.ReceiverBusinessPartnerUUID!=null?this.ReceiverBusinessPartnerUUID.getSimpleValue():null;
        }
        if(propertyIndex==3)
        {
            return this.ReceiverBusinessPartnerInternalID!=null?this.ReceiverBusinessPartnerInternalID:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.RelatedBusinessPartnerUUID!=null?this.RelatedBusinessPartnerUUID.getSimpleValue():null;
        }
        if(propertyIndex==5)
        {
            return this.RelatedBusinessPartnerInternalID!=null?this.RelatedBusinessPartnerInternalID:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.ReceiverRelatedBusinessPartnerUUID!=null?this.ReceiverRelatedBusinessPartnerUUID.getSimpleValue():null;
        }
        if(propertyIndex==7)
        {
            return this.ReceiverRelatedBusinessPartnerInternalID!=null?this.ReceiverRelatedBusinessPartnerInternalID:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==8)
        {
            return this.RoleCode!=null?this.RoleCode.getSimpleValue():null;
        }
        if(propertyIndex==9)
        {
            return this.ValidityPeriod!=null?this.ValidityPeriod:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 10;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "BusinessPartnerUUID";
            info.namespace= "";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "BusinessPartnerInternalID";
            info.namespace= "";
        }
        if(propertyIndex==2)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "ReceiverBusinessPartnerUUID";
            info.namespace= "";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ReceiverBusinessPartnerInternalID";
            info.namespace= "";
        }
        if(propertyIndex==4)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "RelatedBusinessPartnerUUID";
            info.namespace= "";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "RelatedBusinessPartnerInternalID";
            info.namespace= "";
        }
        if(propertyIndex==6)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "ReceiverRelatedBusinessPartnerUUID";
            info.namespace= "";
        }
        if(propertyIndex==7)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ReceiverRelatedBusinessPartnerInternalID";
            info.namespace= "";
        }
        if(propertyIndex==8)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "RoleCode";
            info.namespace= "";
        }
        if(propertyIndex==9)
        {
            info.type = QBSCLOSED_DatePeriod.class;
            info.name = "ValidityPeriod";
            info.namespace= "";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

