package com.exampleariba.aribasoup.gerado;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.2.0
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.math.BigDecimal;

public class QBSBPSUITERplctReqPurgTrms extends AttributeContainer implements KvmSerializable
{

    
    public String CustomsOfficeInternalID;
    
    public String BuyerPartySellerID;
    
    public String PurchaseOrderCurrencyCode;
    
    public QBSCashDiscountTermsCode CashDiscountTermsCode;
    
    public Boolean ReturnItemsEvaluatedReceiptSettlementIndicator;
    
    public String TransportModeCode;
    
    public String TransportServiceLevelCode;
    
    public QBSPriceSpecificationSupplierGroupCode PriceSpecificationSupplierGroupCode;
    
    public String PriceSpecificationDeterminationDateTypeCode;
    
    public QBSPurchasingDocumentItemConfirmationTypeCode ExpectedPurchasingDocumentItemConfirmationTypeCode;
    
    public QBSMeasureUnitGroupCode MeasureUnitGroupCode;
    
    public QBSCode RoundingProfileCode;
    
    public QBSPlanningCalendarCode DeliveryCyclePlanningCalendarCode;
    
    public QBSPlanningCalendarCode PlanningCyclePlanningCalendarCode;
    
    public QBSCode GoodsMovementItemSortCriterionCode;
    
    public QBSCode LoadBuildingRestrictionProfileCode;
    
    public QBSCode DataTransferProfileCode;
    
    public Boolean PurchasingBlockedIndicator;
    
    public Boolean DeliveryBasedInvoiceVerificationIndicator;
    
    public Boolean EvaluatedReceiptSettlementIndicator;
    
    public Boolean AutomaticPurchaseOrderGenerationAllowedIndicator;
    
    public Boolean PurchaseOrderBySupplierProvidedIndicator;
    
    public Boolean DiscountInKindAllowedIndicator;
    
    public Boolean IndexCompilationForSubsequentSettlementAllowedIndicator;
    
    public Boolean DocumentIndexAllowedIndicator;
    
    public Boolean AgencyBusinessRelevanceIndicator;
    
    public Boolean RevaluationAllowedIndicator;
    
    public Boolean ServiceBasedInvoiceVerificationIndicator;
    
    public Boolean SubsequentSettlementApplyIndicator;
    
    public Boolean BusinessVolumeComparisonRequiredIndicator;
    
    public Boolean PricingRelevanceIndicator;
    
    public Boolean RackJobbingIncludedIndicator;
    
    public QBSCode PriceMakingAgreementTypeCode;
    
    public QBSAmount OrderMinimumAmount;
    
    public String PlannedDeliveryDuration;
    
    public BigDecimal SalesVolumeFulfillmentPercent;
    
    public String PurchaseOrderConfirmationRequirementCode;
    
    public String InvoiceConfirmationRequirementCode;
    
    public String FollowUpDespatchedDeliveryNotificationRequirementCode;
    
    public String FollowUpGoodsReceiptRequestRequirementCode;
    
    public QBSIncoterms Incoterms;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,QBSExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,QBSExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("CustomsOfficeInternalID"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.CustomsOfficeInternalID = j.toString();
                    }
                }
                else{
                    this.CustomsOfficeInternalID = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("BuyerPartySellerID"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.BuyerPartySellerID = j.toString();
                    }
                }
                else{
                    this.BuyerPartySellerID = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("PurchaseOrderCurrencyCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.PurchaseOrderCurrencyCode = j.toString();
                    }
                }
                else{
                    this.PurchaseOrderCurrencyCode = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("CashDiscountTermsCode"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.CashDiscountTermsCode = (QBSCashDiscountTermsCode)__envelope.get(j,QBSCashDiscountTermsCode.class,false);
            }
            return true;
        }
        if (info.name.equals("ReturnItemsEvaluatedReceiptSettlementIndicator"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ReturnItemsEvaluatedReceiptSettlementIndicator = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.ReturnItemsEvaluatedReceiptSettlementIndicator = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("TransportModeCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.TransportModeCode = j.toString();
                    }
                }
                else{
                    this.TransportModeCode = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("TransportServiceLevelCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.TransportServiceLevelCode = j.toString();
                    }
                }
                else{
                    this.TransportServiceLevelCode = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("PriceSpecificationSupplierGroupCode"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.PriceSpecificationSupplierGroupCode = (QBSPriceSpecificationSupplierGroupCode)__envelope.get(j,QBSPriceSpecificationSupplierGroupCode.class,false);
            }
            return true;
        }
        if (info.name.equals("PriceSpecificationDeterminationDateTypeCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.PriceSpecificationDeterminationDateTypeCode = j.toString();
                    }
                }
                else{
                    this.PriceSpecificationDeterminationDateTypeCode = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("ExpectedPurchasingDocumentItemConfirmationTypeCode"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.ExpectedPurchasingDocumentItemConfirmationTypeCode = (QBSPurchasingDocumentItemConfirmationTypeCode)__envelope.get(j,QBSPurchasingDocumentItemConfirmationTypeCode.class,false);
            }
            return true;
        }
        if (info.name.equals("MeasureUnitGroupCode"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.MeasureUnitGroupCode = (QBSMeasureUnitGroupCode)__envelope.get(j,QBSMeasureUnitGroupCode.class,false);
            }
            return true;
        }
        if (info.name.equals("RoundingProfileCode"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.RoundingProfileCode = (QBSCode)__envelope.get(j,QBSCode.class,false);
            }
            return true;
        }
        if (info.name.equals("DeliveryCyclePlanningCalendarCode"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.DeliveryCyclePlanningCalendarCode = (QBSPlanningCalendarCode)__envelope.get(j,QBSPlanningCalendarCode.class,false);
            }
            return true;
        }
        if (info.name.equals("PlanningCyclePlanningCalendarCode"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.PlanningCyclePlanningCalendarCode = (QBSPlanningCalendarCode)__envelope.get(j,QBSPlanningCalendarCode.class,false);
            }
            return true;
        }
        if (info.name.equals("GoodsMovementItemSortCriterionCode"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.GoodsMovementItemSortCriterionCode = (QBSCode)__envelope.get(j,QBSCode.class,false);
            }
            return true;
        }
        if (info.name.equals("LoadBuildingRestrictionProfileCode"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.LoadBuildingRestrictionProfileCode = (QBSCode)__envelope.get(j,QBSCode.class,false);
            }
            return true;
        }
        if (info.name.equals("DataTransferProfileCode"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.DataTransferProfileCode = (QBSCode)__envelope.get(j,QBSCode.class,false);
            }
            return true;
        }
        if (info.name.equals("PurchasingBlockedIndicator"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.PurchasingBlockedIndicator = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.PurchasingBlockedIndicator = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("DeliveryBasedInvoiceVerificationIndicator"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.DeliveryBasedInvoiceVerificationIndicator = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.DeliveryBasedInvoiceVerificationIndicator = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("EvaluatedReceiptSettlementIndicator"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.EvaluatedReceiptSettlementIndicator = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.EvaluatedReceiptSettlementIndicator = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("AutomaticPurchaseOrderGenerationAllowedIndicator"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.AutomaticPurchaseOrderGenerationAllowedIndicator = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.AutomaticPurchaseOrderGenerationAllowedIndicator = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("PurchaseOrderBySupplierProvidedIndicator"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.PurchaseOrderBySupplierProvidedIndicator = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.PurchaseOrderBySupplierProvidedIndicator = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("DiscountInKindAllowedIndicator"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.DiscountInKindAllowedIndicator = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.DiscountInKindAllowedIndicator = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("IndexCompilationForSubsequentSettlementAllowedIndicator"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.IndexCompilationForSubsequentSettlementAllowedIndicator = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.IndexCompilationForSubsequentSettlementAllowedIndicator = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("DocumentIndexAllowedIndicator"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.DocumentIndexAllowedIndicator = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.DocumentIndexAllowedIndicator = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("AgencyBusinessRelevanceIndicator"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.AgencyBusinessRelevanceIndicator = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.AgencyBusinessRelevanceIndicator = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("RevaluationAllowedIndicator"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.RevaluationAllowedIndicator = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.RevaluationAllowedIndicator = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ServiceBasedInvoiceVerificationIndicator"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ServiceBasedInvoiceVerificationIndicator = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.ServiceBasedInvoiceVerificationIndicator = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("SubsequentSettlementApplyIndicator"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.SubsequentSettlementApplyIndicator = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.SubsequentSettlementApplyIndicator = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("BusinessVolumeComparisonRequiredIndicator"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.BusinessVolumeComparisonRequiredIndicator = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.BusinessVolumeComparisonRequiredIndicator = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("PricingRelevanceIndicator"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.PricingRelevanceIndicator = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.PricingRelevanceIndicator = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("RackJobbingIncludedIndicator"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.RackJobbingIncludedIndicator = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.RackJobbingIncludedIndicator = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("PriceMakingAgreementTypeCode"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.PriceMakingAgreementTypeCode = (QBSCode)__envelope.get(j,QBSCode.class,false);
            }
            return true;
        }
        if (info.name.equals("OrderMinimumAmount"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.OrderMinimumAmount = (QBSAmount)__envelope.get(j,QBSAmount.class,false);
            }
            return true;
        }
        if (info.name.equals("PlannedDeliveryDuration"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.PlannedDeliveryDuration = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.PlannedDeliveryDuration = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("SalesVolumeFulfillmentPercent"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.SalesVolumeFulfillmentPercent = new BigDecimal(j.toString());
                    }
                }
                else if (obj instanceof BigDecimal){
                    this.SalesVolumeFulfillmentPercent = (BigDecimal)obj;
                }
            }
            return true;
        }
        if (info.name.equals("PurchaseOrderConfirmationRequirementCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.PurchaseOrderConfirmationRequirementCode = j.toString();
                    }
                }
                else{
                    this.PurchaseOrderConfirmationRequirementCode = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("InvoiceConfirmationRequirementCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.InvoiceConfirmationRequirementCode = j.toString();
                    }
                }
                else{
                    this.InvoiceConfirmationRequirementCode = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("FollowUpDespatchedDeliveryNotificationRequirementCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.FollowUpDespatchedDeliveryNotificationRequirementCode = j.toString();
                    }
                }
                else{
                    this.FollowUpDespatchedDeliveryNotificationRequirementCode = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("FollowUpGoodsReceiptRequestRequirementCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.FollowUpGoodsReceiptRequestRequirementCode = j.toString();
                    }
                }
                else{
                    this.FollowUpGoodsReceiptRequestRequirementCode = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("Incoterms"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Incoterms = (QBSIncoterms)__envelope.get(j,QBSIncoterms.class,false);
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.CustomsOfficeInternalID!=null?this.CustomsOfficeInternalID:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.BuyerPartySellerID!=null?this.BuyerPartySellerID:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.PurchaseOrderCurrencyCode!=null?this.PurchaseOrderCurrencyCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.CashDiscountTermsCode!=null?this.CashDiscountTermsCode.getSimpleValue():null;
        }
        if(propertyIndex==4)
        {
            return this.ReturnItemsEvaluatedReceiptSettlementIndicator!=null?this.ReturnItemsEvaluatedReceiptSettlementIndicator:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.TransportModeCode!=null?this.TransportModeCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.TransportServiceLevelCode!=null?this.TransportServiceLevelCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==7)
        {
            return this.PriceSpecificationSupplierGroupCode!=null?this.PriceSpecificationSupplierGroupCode.getSimpleValue():null;
        }
        if(propertyIndex==8)
        {
            return this.PriceSpecificationDeterminationDateTypeCode!=null?this.PriceSpecificationDeterminationDateTypeCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==9)
        {
            return this.ExpectedPurchasingDocumentItemConfirmationTypeCode!=null?this.ExpectedPurchasingDocumentItemConfirmationTypeCode.getSimpleValue():null;
        }
        if(propertyIndex==10)
        {
            return this.MeasureUnitGroupCode!=null?this.MeasureUnitGroupCode.getSimpleValue():null;
        }
        if(propertyIndex==11)
        {
            return this.RoundingProfileCode!=null?this.RoundingProfileCode.getSimpleValue():null;
        }
        if(propertyIndex==12)
        {
            return this.DeliveryCyclePlanningCalendarCode!=null?this.DeliveryCyclePlanningCalendarCode.getSimpleValue():null;
        }
        if(propertyIndex==13)
        {
            return this.PlanningCyclePlanningCalendarCode!=null?this.PlanningCyclePlanningCalendarCode.getSimpleValue():null;
        }
        if(propertyIndex==14)
        {
            return this.GoodsMovementItemSortCriterionCode!=null?this.GoodsMovementItemSortCriterionCode.getSimpleValue():null;
        }
        if(propertyIndex==15)
        {
            return this.LoadBuildingRestrictionProfileCode!=null?this.LoadBuildingRestrictionProfileCode.getSimpleValue():null;
        }
        if(propertyIndex==16)
        {
            return this.DataTransferProfileCode!=null?this.DataTransferProfileCode.getSimpleValue():null;
        }
        if(propertyIndex==17)
        {
            return this.PurchasingBlockedIndicator!=null?this.PurchasingBlockedIndicator:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==18)
        {
            return this.DeliveryBasedInvoiceVerificationIndicator!=null?this.DeliveryBasedInvoiceVerificationIndicator:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==19)
        {
            return this.EvaluatedReceiptSettlementIndicator!=null?this.EvaluatedReceiptSettlementIndicator:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==20)
        {
            return this.AutomaticPurchaseOrderGenerationAllowedIndicator!=null?this.AutomaticPurchaseOrderGenerationAllowedIndicator:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==21)
        {
            return this.PurchaseOrderBySupplierProvidedIndicator!=null?this.PurchaseOrderBySupplierProvidedIndicator:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==22)
        {
            return this.DiscountInKindAllowedIndicator!=null?this.DiscountInKindAllowedIndicator:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==23)
        {
            return this.IndexCompilationForSubsequentSettlementAllowedIndicator!=null?this.IndexCompilationForSubsequentSettlementAllowedIndicator:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==24)
        {
            return this.DocumentIndexAllowedIndicator!=null?this.DocumentIndexAllowedIndicator:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==25)
        {
            return this.AgencyBusinessRelevanceIndicator!=null?this.AgencyBusinessRelevanceIndicator:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==26)
        {
            return this.RevaluationAllowedIndicator!=null?this.RevaluationAllowedIndicator:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==27)
        {
            return this.ServiceBasedInvoiceVerificationIndicator!=null?this.ServiceBasedInvoiceVerificationIndicator:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==28)
        {
            return this.SubsequentSettlementApplyIndicator!=null?this.SubsequentSettlementApplyIndicator:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==29)
        {
            return this.BusinessVolumeComparisonRequiredIndicator!=null?this.BusinessVolumeComparisonRequiredIndicator:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==30)
        {
            return this.PricingRelevanceIndicator!=null?this.PricingRelevanceIndicator:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==31)
        {
            return this.RackJobbingIncludedIndicator!=null?this.RackJobbingIncludedIndicator:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==32)
        {
            return this.PriceMakingAgreementTypeCode!=null?this.PriceMakingAgreementTypeCode.getSimpleValue():null;
        }
        if(propertyIndex==33)
        {
            return this.OrderMinimumAmount!=null?this.OrderMinimumAmount.getSimpleValue():null;
        }
        if(propertyIndex==34)
        {
            return this.PlannedDeliveryDuration!=null?this.PlannedDeliveryDuration:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==35)
        {
            return this.SalesVolumeFulfillmentPercent!=null?this.SalesVolumeFulfillmentPercent.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==36)
        {
            return this.PurchaseOrderConfirmationRequirementCode!=null?this.PurchaseOrderConfirmationRequirementCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==37)
        {
            return this.InvoiceConfirmationRequirementCode!=null?this.InvoiceConfirmationRequirementCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==38)
        {
            return this.FollowUpDespatchedDeliveryNotificationRequirementCode!=null?this.FollowUpDespatchedDeliveryNotificationRequirementCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==39)
        {
            return this.FollowUpGoodsReceiptRequestRequirementCode!=null?this.FollowUpGoodsReceiptRequestRequirementCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==40)
        {
            return this.Incoterms!=null?this.Incoterms:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 41;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "CustomsOfficeInternalID";
            info.namespace= "";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "BuyerPartySellerID";
            info.namespace= "";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "PurchaseOrderCurrencyCode";
            info.namespace= "";
        }
        if(propertyIndex==3)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "CashDiscountTermsCode";
            info.namespace= "";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "ReturnItemsEvaluatedReceiptSettlementIndicator";
            info.namespace= "";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "TransportModeCode";
            info.namespace= "";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "TransportServiceLevelCode";
            info.namespace= "";
        }
        if(propertyIndex==7)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "PriceSpecificationSupplierGroupCode";
            info.namespace= "";
        }
        if(propertyIndex==8)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "PriceSpecificationDeterminationDateTypeCode";
            info.namespace= "";
        }
        if(propertyIndex==9)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "ExpectedPurchasingDocumentItemConfirmationTypeCode";
            info.namespace= "";
        }
        if(propertyIndex==10)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "MeasureUnitGroupCode";
            info.namespace= "";
        }
        if(propertyIndex==11)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "RoundingProfileCode";
            info.namespace= "";
        }
        if(propertyIndex==12)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "DeliveryCyclePlanningCalendarCode";
            info.namespace= "";
        }
        if(propertyIndex==13)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "PlanningCyclePlanningCalendarCode";
            info.namespace= "";
        }
        if(propertyIndex==14)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "GoodsMovementItemSortCriterionCode";
            info.namespace= "";
        }
        if(propertyIndex==15)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "LoadBuildingRestrictionProfileCode";
            info.namespace= "";
        }
        if(propertyIndex==16)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "DataTransferProfileCode";
            info.namespace= "";
        }
        if(propertyIndex==17)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "PurchasingBlockedIndicator";
            info.namespace= "";
        }
        if(propertyIndex==18)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "DeliveryBasedInvoiceVerificationIndicator";
            info.namespace= "";
        }
        if(propertyIndex==19)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "EvaluatedReceiptSettlementIndicator";
            info.namespace= "";
        }
        if(propertyIndex==20)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "AutomaticPurchaseOrderGenerationAllowedIndicator";
            info.namespace= "";
        }
        if(propertyIndex==21)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "PurchaseOrderBySupplierProvidedIndicator";
            info.namespace= "";
        }
        if(propertyIndex==22)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "DiscountInKindAllowedIndicator";
            info.namespace= "";
        }
        if(propertyIndex==23)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "IndexCompilationForSubsequentSettlementAllowedIndicator";
            info.namespace= "";
        }
        if(propertyIndex==24)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "DocumentIndexAllowedIndicator";
            info.namespace= "";
        }
        if(propertyIndex==25)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "AgencyBusinessRelevanceIndicator";
            info.namespace= "";
        }
        if(propertyIndex==26)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "RevaluationAllowedIndicator";
            info.namespace= "";
        }
        if(propertyIndex==27)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "ServiceBasedInvoiceVerificationIndicator";
            info.namespace= "";
        }
        if(propertyIndex==28)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "SubsequentSettlementApplyIndicator";
            info.namespace= "";
        }
        if(propertyIndex==29)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "BusinessVolumeComparisonRequiredIndicator";
            info.namespace= "";
        }
        if(propertyIndex==30)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "PricingRelevanceIndicator";
            info.namespace= "";
        }
        if(propertyIndex==31)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "RackJobbingIncludedIndicator";
            info.namespace= "";
        }
        if(propertyIndex==32)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "PriceMakingAgreementTypeCode";
            info.namespace= "";
        }
        if(propertyIndex==33)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "OrderMinimumAmount";
            info.namespace= "";
        }
        if(propertyIndex==34)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "PlannedDeliveryDuration";
            info.namespace= "";
        }
        if(propertyIndex==35)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "SalesVolumeFulfillmentPercent";
            info.namespace= "";
        }
        if(propertyIndex==36)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "PurchaseOrderConfirmationRequirementCode";
            info.namespace= "";
        }
        if(propertyIndex==37)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "InvoiceConfirmationRequirementCode";
            info.namespace= "";
        }
        if(propertyIndex==38)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "FollowUpDespatchedDeliveryNotificationRequirementCode";
            info.namespace= "";
        }
        if(propertyIndex==39)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "FollowUpGoodsReceiptRequestRequirementCode";
            info.namespace= "";
        }
        if(propertyIndex==40)
        {
            info.type = QBSIncoterms.class;
            info.name = "Incoterms";
            info.namespace= "";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

