package com.exampleariba.aribasoup.gerado;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.2.0
//
// Created by Quasar Development 
//
//---------------------------------------------------


import org.ksoap2.serialization.*;
import java.math.BigDecimal;

public class QBSGenericCustomField  
{

    
    public String value;
    
    public String name;
    
    public QBSEnums.GenericCustomFieldType type=QBSEnums.GenericCustomFieldType.Code;
    
    public String title;
    
    public String description;
    
    public String languageCode;
    
    public String table;
    
    public String field;
    
    public String checkTable;
    
    public String receiverTable;
    
    public String receiverField;
    
    public String receiverCheckTable;
    
    public Integer maxLength=0;
    
    public Integer minLength=0;
    
    public String pattern;
    
    public Integer totalDigits=0;
    
    public Integer fractionDigits=0;
    
    public BigDecimal maxInclusive=BigDecimal.ZERO;
    
    public BigDecimal minInclusive=BigDecimal.ZERO;
    
    public String displayRestrictions;
    
    public String editRestrictions;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,QBSExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(!(inObj instanceof SoapObject))
        {
            java.lang.Object j =(java.lang.Object)inObj;
            value = j.toString();
        }
        if (inObj.hasAttribute("name"))
        {	
            java.lang.Object j = inObj.getAttribute("name");
            if (j != null)
            {
                name = j.toString();
            }
        }
        if (inObj.hasAttribute("type"))
        {	
            java.lang.Object j = inObj.getAttribute("type");
            if (j != null)
            {
                type = QBSEnums.GenericCustomFieldType.fromString(j.toString());
            }
        }
        if (inObj.hasAttribute("title"))
        {	
            java.lang.Object j = inObj.getAttribute("title");
            if (j != null)
            {
                title = j.toString();
            }
        }
        if (inObj.hasAttribute("description"))
        {	
            java.lang.Object j = inObj.getAttribute("description");
            if (j != null)
            {
                description = j.toString();
            }
        }
        if (inObj.hasAttribute("languageCode"))
        {	
            java.lang.Object j = inObj.getAttribute("languageCode");
            if (j != null)
            {
                languageCode = j.toString();
            }
        }
        if (inObj.hasAttribute("table"))
        {	
            java.lang.Object j = inObj.getAttribute("table");
            if (j != null)
            {
                table = j.toString();
            }
        }
        if (inObj.hasAttribute("field"))
        {	
            java.lang.Object j = inObj.getAttribute("field");
            if (j != null)
            {
                field = j.toString();
            }
        }
        if (inObj.hasAttribute("checkTable"))
        {	
            java.lang.Object j = inObj.getAttribute("checkTable");
            if (j != null)
            {
                checkTable = j.toString();
            }
        }
        if (inObj.hasAttribute("receiverTable"))
        {	
            java.lang.Object j = inObj.getAttribute("receiverTable");
            if (j != null)
            {
                receiverTable = j.toString();
            }
        }
        if (inObj.hasAttribute("receiverField"))
        {	
            java.lang.Object j = inObj.getAttribute("receiverField");
            if (j != null)
            {
                receiverField = j.toString();
            }
        }
        if (inObj.hasAttribute("receiverCheckTable"))
        {	
            java.lang.Object j = inObj.getAttribute("receiverCheckTable");
            if (j != null)
            {
                receiverCheckTable = j.toString();
            }
        }
        if (inObj.hasAttribute("maxLength"))
        {	
            java.lang.Object j = inObj.getAttribute("maxLength");
            if (j != null)
            {
                maxLength = Integer.parseInt(j.toString());
            }
        }
        if (inObj.hasAttribute("minLength"))
        {	
            java.lang.Object j = inObj.getAttribute("minLength");
            if (j != null)
            {
                minLength = Integer.parseInt(j.toString());
            }
        }
        if (inObj.hasAttribute("pattern"))
        {	
            java.lang.Object j = inObj.getAttribute("pattern");
            if (j != null)
            {
                pattern = j.toString();
            }
        }
        if (inObj.hasAttribute("totalDigits"))
        {	
            java.lang.Object j = inObj.getAttribute("totalDigits");
            if (j != null)
            {
                totalDigits = Integer.parseInt(j.toString());
            }
        }
        if (inObj.hasAttribute("fractionDigits"))
        {	
            java.lang.Object j = inObj.getAttribute("fractionDigits");
            if (j != null)
            {
                fractionDigits = Integer.parseInt(j.toString());
            }
        }
        if (inObj.hasAttribute("maxInclusive"))
        {	
            java.lang.Object j = inObj.getAttribute("maxInclusive");
            if (j != null)
            {
                maxInclusive = new BigDecimal(j.toString());
            }
        }
        if (inObj.hasAttribute("minInclusive"))
        {	
            java.lang.Object j = inObj.getAttribute("minInclusive");
            if (j != null)
            {
                minInclusive = new BigDecimal(j.toString());
            }
        }
        if (inObj.hasAttribute("displayRestrictions"))
        {	
            java.lang.Object j = inObj.getAttribute("displayRestrictions");
            if (j != null)
            {
                displayRestrictions = j.toString();
            }
        }
        if (inObj.hasAttribute("editRestrictions"))
        {	
            java.lang.Object j = inObj.getAttribute("editRestrictions");
            if (j != null)
            {
                editRestrictions = j.toString();
            }
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,QBSExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("value"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.value = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.value = (String)obj;
                }
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    
    public Object getSimpleValue()
    {
        Object value=this.value != null ? this.value.toString() : "";
        SoapPrimitive primitive = new SoapPrimitive("", "value",value);
        
        if (this.name != null)
        {
            AttributeInfo attrInfo = new AttributeInfo();
            attrInfo.setName("name");
            attrInfo.setValue(this.name);
            attrInfo.setNamespace("");
            primitive.addAttribute(attrInfo);
        }
        if (this.type != null)
        {
            AttributeInfo attrInfo = new AttributeInfo();
            attrInfo.setName("type");
            attrInfo.setValue(this.type);
            attrInfo.setNamespace("");
            primitive.addAttribute(attrInfo);
        }
        if (this.title != null)
        {
            AttributeInfo attrInfo = new AttributeInfo();
            attrInfo.setName("title");
            attrInfo.setValue(this.title);
            attrInfo.setNamespace("");
            primitive.addAttribute(attrInfo);
        }
        if (this.description != null)
        {
            AttributeInfo attrInfo = new AttributeInfo();
            attrInfo.setName("description");
            attrInfo.setValue(this.description);
            attrInfo.setNamespace("");
            primitive.addAttribute(attrInfo);
        }
        if (this.languageCode != null)
        {
            AttributeInfo attrInfo = new AttributeInfo();
            attrInfo.setName("languageCode");
            attrInfo.setValue(this.languageCode);
            attrInfo.setNamespace("");
            primitive.addAttribute(attrInfo);
        }
        if (this.table != null)
        {
            AttributeInfo attrInfo = new AttributeInfo();
            attrInfo.setName("table");
            attrInfo.setValue(this.table);
            attrInfo.setNamespace("");
            primitive.addAttribute(attrInfo);
        }
        if (this.field != null)
        {
            AttributeInfo attrInfo = new AttributeInfo();
            attrInfo.setName("field");
            attrInfo.setValue(this.field);
            attrInfo.setNamespace("");
            primitive.addAttribute(attrInfo);
        }
        if (this.checkTable != null)
        {
            AttributeInfo attrInfo = new AttributeInfo();
            attrInfo.setName("checkTable");
            attrInfo.setValue(this.checkTable);
            attrInfo.setNamespace("");
            primitive.addAttribute(attrInfo);
        }
        if (this.receiverTable != null)
        {
            AttributeInfo attrInfo = new AttributeInfo();
            attrInfo.setName("receiverTable");
            attrInfo.setValue(this.receiverTable);
            attrInfo.setNamespace("");
            primitive.addAttribute(attrInfo);
        }
        if (this.receiverField != null)
        {
            AttributeInfo attrInfo = new AttributeInfo();
            attrInfo.setName("receiverField");
            attrInfo.setValue(this.receiverField);
            attrInfo.setNamespace("");
            primitive.addAttribute(attrInfo);
        }
        if (this.receiverCheckTable != null)
        {
            AttributeInfo attrInfo = new AttributeInfo();
            attrInfo.setName("receiverCheckTable");
            attrInfo.setValue(this.receiverCheckTable);
            attrInfo.setNamespace("");
            primitive.addAttribute(attrInfo);
        }
        if (this.maxLength != null)
        {
            AttributeInfo attrInfo = new AttributeInfo();
            attrInfo.setName("maxLength");
            attrInfo.setValue(this.maxLength);
            attrInfo.setNamespace("");
            primitive.addAttribute(attrInfo);
        }
        if (this.minLength != null)
        {
            AttributeInfo attrInfo = new AttributeInfo();
            attrInfo.setName("minLength");
            attrInfo.setValue(this.minLength);
            attrInfo.setNamespace("");
            primitive.addAttribute(attrInfo);
        }
        if (this.pattern != null)
        {
            AttributeInfo attrInfo = new AttributeInfo();
            attrInfo.setName("pattern");
            attrInfo.setValue(this.pattern);
            attrInfo.setNamespace("");
            primitive.addAttribute(attrInfo);
        }
        if (this.totalDigits != null)
        {
            AttributeInfo attrInfo = new AttributeInfo();
            attrInfo.setName("totalDigits");
            attrInfo.setValue(this.totalDigits);
            attrInfo.setNamespace("");
            primitive.addAttribute(attrInfo);
        }
        if (this.fractionDigits != null)
        {
            AttributeInfo attrInfo = new AttributeInfo();
            attrInfo.setName("fractionDigits");
            attrInfo.setValue(this.fractionDigits);
            attrInfo.setNamespace("");
            primitive.addAttribute(attrInfo);
        }
        if (this.maxInclusive != null)
        {
            AttributeInfo attrInfo = new AttributeInfo();
            attrInfo.setName("maxInclusive");
            attrInfo.setValue(this.maxInclusive);
            attrInfo.setNamespace("");
            primitive.addAttribute(attrInfo);
        }
        if (this.minInclusive != null)
        {
            AttributeInfo attrInfo = new AttributeInfo();
            attrInfo.setName("minInclusive");
            attrInfo.setValue(this.minInclusive);
            attrInfo.setNamespace("");
            primitive.addAttribute(attrInfo);
        }
        if (this.displayRestrictions != null)
        {
            AttributeInfo attrInfo = new AttributeInfo();
            attrInfo.setName("displayRestrictions");
            attrInfo.setValue(this.displayRestrictions);
            attrInfo.setNamespace("");
            primitive.addAttribute(attrInfo);
        }
        if (this.editRestrictions != null)
        {
            AttributeInfo attrInfo = new AttributeInfo();
            attrInfo.setName("editRestrictions");
            attrInfo.setValue(this.editRestrictions);
            attrInfo.setNamespace("");
            primitive.addAttribute(attrInfo);
        }
        return primitive;
    }    
}

