package com.exampleariba.aribasoup.gerado;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.2.0
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.util.ArrayList;
import org.ksoap2.serialization.PropertyInfo;

public class QBSLog extends AttributeContainer implements KvmSerializable
{

    
    public String BusinessDocumentProcessingResultCode;
    
    public String MaximumLogItemSeverityCode;
    
    public ArrayList< QBSLogItem> Item =new ArrayList<QBSLogItem >();
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,QBSExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,QBSExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("BusinessDocumentProcessingResultCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.BusinessDocumentProcessingResultCode = j.toString();
                    }
                }
                else{
                    this.BusinessDocumentProcessingResultCode = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("MaximumLogItemSeverityCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.MaximumLogItemSeverityCode = j.toString();
                    }
                }
                else{
                    this.MaximumLogItemSeverityCode = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("Item"))
        {
            if(obj!=null)
            {
                if(this.Item==null)
                {
                    this.Item = new java.util.ArrayList< QBSLogItem>();
                }
                java.lang.Object j =obj;
                QBSLogItem j1= (QBSLogItem)__envelope.get(j,QBSLogItem.class,false);
                this.Item.add(j1);
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.BusinessDocumentProcessingResultCode!=null?this.BusinessDocumentProcessingResultCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.MaximumLogItemSeverityCode!=null?this.MaximumLogItemSeverityCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex>=2 && propertyIndex < 2+this.Item.size())
        {
            java.lang.Object Item = this.Item.get(propertyIndex-(2));
            return Item!=null?Item:SoapPrimitive.NullNilElement;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 2+Item.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "BusinessDocumentProcessingResultCode";
            info.namespace= "";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "MaximumLogItemSeverityCode";
            info.namespace= "";
        }
        if(propertyIndex>=2 && propertyIndex < 2+this.Item.size())
        {
            info.type = QBSLogItem.class;
            info.name = "Item";
            info.namespace= "";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

