package com.exampleariba.aribasoup.gerado;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.2.0
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class QBSOrganisationName extends AttributeContainer implements KvmSerializable
{

    
    public QBSFormOfAddressCode FormOfAddressCode;
    
    public String FirstLineName;
    
    public String SecondLineName;
    
    public String ThirdLineName;
    
    public String FourthLineName;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,QBSExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,QBSExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("FormOfAddressCode"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.FormOfAddressCode = (QBSFormOfAddressCode)__envelope.get(j,QBSFormOfAddressCode.class,false);
            }
            return true;
        }
        if (info.name.equals("FirstLineName"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.FirstLineName = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.FirstLineName = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("SecondLineName"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.SecondLineName = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.SecondLineName = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ThirdLineName"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ThirdLineName = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.ThirdLineName = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("FourthLineName"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.FourthLineName = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.FourthLineName = (String)obj;
                }
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.FormOfAddressCode!=null?this.FormOfAddressCode.getSimpleValue():null;
        }
        if(propertyIndex==1)
        {
            return this.FirstLineName!=null?this.FirstLineName:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.SecondLineName!=null?this.SecondLineName:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.ThirdLineName!=null?this.ThirdLineName:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.FourthLineName!=null?this.FourthLineName:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 5;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "FormOfAddressCode";
            info.namespace= "";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "FirstLineName";
            info.namespace= "";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "SecondLineName";
            info.namespace= "";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ThirdLineName";
            info.namespace= "";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "FourthLineName";
            info.namespace= "";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

