package com.exampleariba.aribasoup.gerado;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.2.0
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class QBSPollingMessage extends AttributeContainer implements KvmSerializable
{

    
    public QBSBPSUITEBulkRplctReqMsg BusinessPartnerSUITEBulkReplicateRequest;
    
    public QBSBPSUITEBulkRplctConfMsg BusinessPartnerSUITEBulkReplicateConfirmation;
    
    public QBSBPRelshpSUITEBulkRplctReqMsg BusinessPartnerRelationshipSUITEBulkReplicateRequest;
    
    public QBSBPRelshpSUITEBulkRplctConfMsg BusinessPartnerRelationshipSUITEBulkReplicateConfirmation;
    
    public String inboundServiceName;
    
    public String timestamp;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,QBSExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }
        if (inObj.hasAttribute("inboundServiceName"))
        {	
            java.lang.Object j = inObj.getAttribute("inboundServiceName");
            if (j != null)
            {
                inboundServiceName = j.toString();
            }
        }
        if (inObj.hasAttribute("timestamp"))
        {	
            java.lang.Object j = inObj.getAttribute("timestamp");
            if (j != null)
            {
                timestamp = j.toString();
            }
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,QBSExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("BusinessPartnerSUITEBulkReplicateRequest"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.BusinessPartnerSUITEBulkReplicateRequest = (QBSBPSUITEBulkRplctReqMsg)__envelope.get(j,QBSBPSUITEBulkRplctReqMsg.class,false);
            }
            return true;
        }
        if (info.name.equals("BusinessPartnerSUITEBulkReplicateConfirmation"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.BusinessPartnerSUITEBulkReplicateConfirmation = (QBSBPSUITEBulkRplctConfMsg)__envelope.get(j,QBSBPSUITEBulkRplctConfMsg.class,false);
            }
            return true;
        }
        if (info.name.equals("BusinessPartnerRelationshipSUITEBulkReplicateRequest"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.BusinessPartnerRelationshipSUITEBulkReplicateRequest = (QBSBPRelshpSUITEBulkRplctReqMsg)__envelope.get(j,QBSBPRelshpSUITEBulkRplctReqMsg.class,false);
            }
            return true;
        }
        if (info.name.equals("BusinessPartnerRelationshipSUITEBulkReplicateConfirmation"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.BusinessPartnerRelationshipSUITEBulkReplicateConfirmation = (QBSBPRelshpSUITEBulkRplctConfMsg)__envelope.get(j,QBSBPRelshpSUITEBulkRplctConfMsg.class,false);
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.BusinessPartnerSUITEBulkReplicateRequest!=null?this.BusinessPartnerSUITEBulkReplicateRequest:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.BusinessPartnerSUITEBulkReplicateConfirmation!=null?this.BusinessPartnerSUITEBulkReplicateConfirmation:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.BusinessPartnerRelationshipSUITEBulkReplicateRequest!=null?this.BusinessPartnerRelationshipSUITEBulkReplicateRequest:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.BusinessPartnerRelationshipSUITEBulkReplicateConfirmation!=null?this.BusinessPartnerRelationshipSUITEBulkReplicateConfirmation:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 4;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = QBSBPSUITEBulkRplctReqMsg.class;
            info.name = "BusinessPartnerSUITEBulkReplicateRequest";
            info.namespace= "";
        }
        if(propertyIndex==1)
        {
            info.type = QBSBPSUITEBulkRplctConfMsg.class;
            info.name = "BusinessPartnerSUITEBulkReplicateConfirmation";
            info.namespace= "";
        }
        if(propertyIndex==2)
        {
            info.type = QBSBPRelshpSUITEBulkRplctReqMsg.class;
            info.name = "BusinessPartnerRelationshipSUITEBulkReplicateRequest";
            info.namespace= "";
        }
        if(propertyIndex==3)
        {
            info.type = QBSBPRelshpSUITEBulkRplctConfMsg.class;
            info.name = "BusinessPartnerRelationshipSUITEBulkReplicateConfirmation";
            info.namespace= "";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }



    @Override
    public int getAttributeCount() {
        return 2;
    }
    
    @Override
    public void getAttributeInfo(int index, AttributeInfo info) {
        if(index==0)
        {
            info.name = "inboundServiceName";
            info.namespace= "";
            if(this.inboundServiceName!=null)
            {
                info.setValue(this.inboundServiceName);
            }
            
        }
        if(index==1)
        {
            info.name = "timestamp";
            info.namespace= "";
            if(this.timestamp!=null)
            {
                info.setValue(this.timestamp);
            }
            
        }
    }

    @Override
    public void getAttribute(int i, AttributeInfo attributeInfo) {

    }

    @Override
    public void setAttribute(AttributeInfo attributeInfo) {

    }    
}

