package com.exampleariba.aribasoup.gerado;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.2.0
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class QBSPhoneNumber extends AttributeContainer implements KvmSerializable
{

    
    public String AreaID;
    
    public String SubscriberID;
    
    public String ExtensionID;
    
    public String CountryCode;
    
    public String CountryDiallingCode;
    
    public QBSMEDIUM_Name CountryName;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,QBSExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,QBSExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("AreaID"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.AreaID = j.toString();
                    }
                }
                else{
                    this.AreaID = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("SubscriberID"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.SubscriberID = j.toString();
                    }
                }
                else{
                    this.SubscriberID = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("ExtensionID"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ExtensionID = j.toString();
                    }
                }
                else{
                    this.ExtensionID = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("CountryCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.CountryCode = j.toString();
                    }
                }
                else{
                    this.CountryCode = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("CountryDiallingCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.CountryDiallingCode = j.toString();
                    }
                }
                else{
                    this.CountryDiallingCode = obj.toString();
                }
            }
            return true;
        }
        if (info.name.equals("CountryName"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.CountryName = (QBSMEDIUM_Name)__envelope.get(j,QBSMEDIUM_Name.class,false);
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.AreaID!=null?this.AreaID:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.SubscriberID!=null?this.SubscriberID:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.ExtensionID!=null?this.ExtensionID:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.CountryCode!=null?this.CountryCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.CountryDiallingCode!=null?this.CountryDiallingCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.CountryName!=null?this.CountryName.getSimpleValue():null;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 6;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "AreaID";
            info.namespace= "";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "SubscriberID";
            info.namespace= "";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ExtensionID";
            info.namespace= "";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "CountryCode";
            info.namespace= "";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "CountryDiallingCode";
            info.namespace= "";
        }
        if(propertyIndex==5)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "CountryName";
            info.namespace= "";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

